### ISSUE TITLE
AbstractItem RuntimeException

### ISSUE THREAD

**Issue by AndrazP** [mikepenz/FastAdapter#117]
Hi,
Crashlytics just reported to me a fatal exception in AbstractItem:

> Fatal Exception: java.lang.RuntimeException: You have to provide a ViewHolder with a constructor which takes a view!
       at com.mikepenz.fastadapter.items.AbstractItem$ReflectionBasedViewHolderFactory.create(AbstractItem.java:343)
       at com.mikepenz.fastadapter.items.AbstractItem.getViewHolder(AbstractItem.java:284)
       at com.mikepenz.fastadapter.items.AbstractItem.getViewHolder(AbstractItem.java:233)
       at com.mikepenz.fastadapter.FastAdapter$OnCreateViewHolderListenerImpl.onPreCreateViewHolder(FastAdapter.java:1326)
       at com.mikepenz.fastadapter.FastAdapter.onCreateViewHolder(FastAdapter.java:330)
       at com.mikepenz.fastadapter.AbstractAdapter.onCreateViewHolder(AbstractAdapter.java:128)
       at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:5482)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4707)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4617)
       at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1994)
       at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1390)
       at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1353)
       at android.support.v7.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1180)
       at android.support.v7.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:1031)
       at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:4061)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:788)
       at android.view.Choreographer.doCallbacks(Choreographer.java:591)
       at android.view.Choreographer.doFrame(Choreographer.java:559)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:774)
       at android.os.Handler.handleCallback(Handler.java:808)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:5333)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
       at dalvik.system.NativeStart.main(NativeStart.java)

Any idea what went wrong? I have never expirienced it during development.

**Comment by mikepenz** [comment]
`Fatal Exception: java.lang.RuntimeException: You have to provide a ViewHolder with a constructor which takes a view!`

**Comment by AndrazP** [comment]
Yes. But why did it never occurred during development and testing? It has to be a corner case.

**Comment by mikepenz** [comment]
Either your `ViewHolder` misses the CTOR with the view. or there was some weird `Generics` exception on a specific device. 
In this case you might want to provide an `ItemFactory` and the `getFactory()` method
https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/items/IconItem.java#L75

**Comment by mikepenz** [comment]
https://github.com/mikepenz/FastAdapter#proguard

But yes it is weird that it never happened during testing nor devvelopment. Any pattern on which device and android version this happened. or was it really a one time crash?

**Comment by AndrazP** [comment]
Oh, that's it.
I forgot to implement it in one item (rarely used), I thought it's only for optimization purposes.
Thanks!
