### ISSUE TITLE
Exception Selectable

### ISSUE THREAD

**Issue by artests87** [mikepenz/FastAdapter#118]
Hi, Mike!
I have found some bugs in the perfect FastAdapter.
In your sample, Advanced Sample - Long Click on the internal
SubSubTest 1 - Click on the SubSubTest 2 - Click on the SubTest1 -
Exception!
 Process: com.mikepenz.fastadapter.app, PID: 19737

       java.util.ConcurrentModificationException

           at java.util.TreeMap$MapIterator.stepForward(TreeMap.java:883)

           at java.util.TreeMap$KeySet$1.next(TreeMap.java:959)

           at com.mikepenz.fastadapter.FastAdapter.collapse(FastAdapter.java:986)

           at com.mikepenz.fastadapter.FastAdapter.collapse(FastAdapter.java:958)

           at com.mikepenz.fastadapter.FastAdapter.toggleExpandable(FastAdapter.java:926)

           at com.mikepenz.fastadapter.FastAdapter$1.onClick(FastAdapter.java:355)
....
Best regards,
 Andrei.

**Comment by mikepenz** [comment]
@artests87 Hi. thanks for your report. 
And thank you so much :)

I found the issue and fixed it in the latest version v1.4.5

Best,
Mike

**Comment by artests87** [comment]
Thanks a lot!
Your FastAdapter is the greatest!
