### ISSUE TITLE
IndexOutOfBoundsException

### ISSUE THREAD

**Issue by RR12** [mikepenz/FastAdapter#121]
Hi, first of all thanks for this great library. So this is the first time I implement it into my app. It works great but I have this occasional crash. This sometime happen at the very first time my app opened. Can you point out something that can cause this error, since it doesn't show any part of my code in the stacktrace?

```
Fatal Exception: java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
       at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
       at java.util.ArrayList.get(ArrayList.java:308)
       at com.mikepenz.fastadapter.adapters.ItemAdapter.getAdapterItem(ItemAdapter.java:192)
       at com.mikepenz.fastadapter.FastAdapter.getItem(FastAdapter.java:490)
       at com.mikepenz.fastadapter.FastAdapter.getItemViewType(FastAdapter.java:538)
       at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:4510)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4636)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4617)
       at android.support.v7.widget.LayoutState.next(LayoutState.java:100)
       at android.support.v7.widget.StaggeredGridLayoutManager.fill(StaggeredGridLayoutManager.java:1538)
       at android.support.v7.widget.StaggeredGridLayoutManager.onLayoutChildren(StaggeredGridLayoutManager.java:657)
       at android.support.v7.widget.StaggeredGridLayoutManager.onLayoutChildren(StaggeredGridLayoutManager.java:592)
       at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3028)
       at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2906)
       at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3283)
       at android.view.View.layout(View.java:16075)
       at android.view.ViewGroup.layout(ViewGroup.java:5300)
       at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:596)
       at android.view.View.layout(View.java:16075)
       at android.view.ViewGroup.layout(ViewGroup.java:5300)
       at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1695)
       at android.view.View.layout(View.java:16075)
       at android.view.ViewGroup.layout(ViewGroup.java:5300)
       at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:122)
       at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
       at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1170)
       at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:814)
       at android.view.View.layout(View.java:16075)
       at android.view.ViewGroup.layout(ViewGroup.java:5300)
       at com.jeremyfeinstein.slidingmenu.lib.CustomViewAbove.onLayout(CustomViewAbove.java:476)
       at android.view.View.layout(View.java:16075)
       at android.view.ViewGroup.layout(ViewGroup.java:5300)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1077)
       at android.view.View.layout(View.java:16075)
       at android.view.ViewGroup.layout(ViewGroup.java:5300)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
       at android.view.View.layout(View.java:16075)
       at android.view.ViewGroup.layout(ViewGroup.java:5300)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
       at android.view.View.layout(View.java:16075)
       at android.view.ViewGroup.layout(ViewGroup.java:5300)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
       at android.view.View.layout(View.java:16075)
       at android.view.ViewGroup.layout(ViewGroup.java:5300)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
       at android.view.View.layout(View.java:16075)
       at android.view.ViewGroup.layout(ViewGroup.java:5300)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
       at android.view.View.layout(View.java:16075)
       at android.view.ViewGroup.layout(ViewGroup.java:5300)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2119)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1873)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1073)
```

**Comment by mikepenz** [comment]
@RR12 can you please add some code how you init the `FastAdapter`? The crash is weird. It seems that the `RecyclerView` tries to init and fill the list with items, but there are no items in the list anymore / or the list was altered. So it seems there is some issue there.

**Comment by RR12** [comment]
Here is how I init the adapter and attach it to `RecyclerView` 

````
@Override
    public void onViewCreated(View view, @Nullable Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        
        mRecyclerView.setLayoutManager(getLayoutManager());
        mRecyclerView.addOnScrollListener(new RecyclerView.OnScrollListener() {
            @Override
            public void onScrolled(RecyclerView recyclerView, int dx, int dy) {
                if (mIsRefreshable) {
                    int topRowVerticalPosition = (recyclerView == null || recyclerView.getChildCount() == 0) ? 0 : recyclerView.getChildAt(0).getTop();
                    mRefreshLayout.setEnabled(topRowVerticalPosition >= 0);
                } else {
                    mRefreshLayout.setEnabled(false);
                }
            }
        });
        mAdapter.setHasStableIds(true);
        mRecyclerView.setAdapter(mAdapter);

        mLoadMoreItem = new LoadMoreListItem(new LoadMoreListItem.LoadMoreListener() {
            @Override
            public void onLoadMore() {
                downloadData();
            }
        });

        mAdapter.add(mLoadMoreItem);
        mAdapter.notifyAdapterDataSetChanged();
    }
```

**Comment by mikepenz** [comment]
you do not have to do the following:
```java
mAdapter.notifyAdapterDataSetChanged();
```

This is already all managed by the `FastAdapter` itself

**Comment by RR12** [comment]
okay, so i don't need to call`notifyAdapterDataSetChanged()` anymore? Even for `clear()`, `add()` and `remove()` ?

**Comment by mikepenz** [comment]
@RR12 right. Everything already handled by the `FastAdapter` as long as you call the corresponding methods on the `ItemAdapter`. 

It will correctly call and forward all those `notify` calls for you:
https://github.com/mikepenz/FastAdapter/blob/develop/library/src/main/java/com/mikepenz/fastadapter/adapters/ItemAdapter.java#L422
