### ISSUE TITLE
Expandable function and footerview cause error

### ISSUE THREAD

**Issue by stonecold123** [mikepenz/FastAdapter#156]
I wonder if this is a bug with the Expandable function. 
I found that adding a footerview to the fastItemAdapter is problematic.

When I click on the very last expandable group, its child items would appear above the recycler view list instead of under their parent group. Then an error occurs if I click on the last parent group again:

````
Inconsistency detected. Invalid view holder adapter positionViewHolder{21e958a8 position=18 id=-1, oldPos=18, pLpos:-1 scrap [attachedScrap] tmpDetached no parent}
````

Without the footeradapter, the problem is gone. And the fact that the error only occurs on the last parent group leads me to think there is a conflict between the footeradapter and the expandable function.

Code Example:

````
        fastItemAdapter = new FastItemAdapter<>();
        FooterAdapter<FooterView> footerAdapter = new FooterAdapter();
        fastItemAdapter.withSelectable(true);
        fastItemAdapter.withMultiSelect(true);
        fastItemAdapter.setHasStableIds(false);
        fastItemAdapter.withPositionBasedStateManagement(false);
        RecyclerView recyclerView = (RecyclerView) view.findViewById(R.id.recycle_container);
        recyclerView.setLayoutManager(new LinearLayoutManager(context));
        recyclerView.setAdapter(footerAdapter.wrap(fastItemAdapter));
````

````
E/AndroidRuntime: FATAL EXCEPTION: main Process: com.site, PID: 25452
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{21e958a8 position=18 id=-1, oldPos=18, pLpos:-1 scrap [attachedScrap] tmpDetached no parent}
 at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:4801)
at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4932)
at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4913)
at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2029)
at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:531)
at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1377)
at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:578)
at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3211)
at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:2782)
at android.view.View.measure(View.java:16772)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5139)
at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
at android.view.View.measure(View.java:16772)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5139)
at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
at android.view.View.measure(View.java:16772)
at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1624)
at android.view.View.measure(View.java:16772)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5139)
at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
at android.view.View.measure(View.java:16772)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5139)
at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
at android.view.View.measure(View.java:16772)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5139)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
at android.view.View.measure(View.java:16772)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5139)
at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
at android.view.View.measure(View.java:16772)
at android.support.v4.widget.DrawerLayout.onMeasure(DrawerLayout.java:1079)
at android.view.View.measure(View.java:16772)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5139)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:135)
at android.view.View.measure(View.java:16772)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5139)
at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
at android.view.View.measure(View.java:16772)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5139)
````

**Comment by mikepenz** [comment]
@stonecold123 new version with a fix for this released
