### ISSUE TITLE
Wrong attribute for Android <= API 10

### ISSUE THREAD

**Issue by munsuri** [mikepenz/FastAdapter#164]
Hi!

First of all, thanks for these great libs you have created :)

I've found a bug at <a href="https://github.com/mikepenz/FastAdapter/blob/4260c728632e8261cabf524b30197e9638f94c60/library/src/main/java/com/mikepenz/fastadapter/utils/FastAdapterUIUtils.java#L85">FastAdapterUIUtils.java#L85</a> while running on API 10.

```
 E/AndroidRuntime: FATAL EXCEPTION: main android.content.res.Resources$NotFoundException: Resource ID #0x0
       at android.content.res.Resources.getValue(Resources.java:892)
       at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:365)
       at ....SimpleImageItem.getSelectableBackground(SimpleImageItem.java:115)
       at ....SimpleImageItem.getSelectablePressedBackground(SimpleImageItem.java:101)
       at ....SimpleImageItem.bindView(SimpleImageItem.java:93)
       at ...SimpleImageItem.bindView(SimpleImageItem.java:29)
       at com.mikepenz.fastadapter.FastAdapter$OnBindViewHolderListenerImpl.onBindViewHolder(FastAdapter.java:1662)
       at com.mikepenz.fastadapter.FastAdapter.onBindViewHolder(FastAdapter.java:496)
       at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:5768)
       at com.mikepenz.fastadapter.AbstractAdapter.onBindViewHolder(AbstractAdapter.java:151)
       at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:5801)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5037)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4913)
       at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2029)
       at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1414)
       at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1377)
       at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:578)
       at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3260)
       at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3069)
       at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3518)
       at android.view.View.layout(View.java:7175)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:912)
       at android.view.View.layout(View.java:7175)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:912)
       at android.view.View.layout(View.java:7175)
       at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1191)
       at android.view.View.layout(View.java:7175)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:338)
       at android.view.View.layout(View.java:7175)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:338)
       at android.view.View.layout(View.java:7175)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:338)
       at android.view.View.layout(View.java:7175)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:338)
       at android.view.View.layout(View.java:7175)
       at android.view.ViewRoot.performTraversals(ViewRoot.java:1140)
       at android.view.ViewRoot.handleMessage(ViewRoot.java:1859)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:130)
       at android.app.ActivityThread.main(ActivityThread.java:3683)
       at java.lang.reflect.Method.invokeNative(Native Method)
       at java.lang.reflect.Method.invoke(Method.java:507)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
       at dalvik.system.NativeStart.main(Native Method)
```

And I solved it by replacing <b>android.R.attr.itemBackground</b> for <b>R.attr.selectableItemBackground</b>

**Comment by mikepenz** [comment]
@munsuri this is meant to work starting with API 11 as the sample app does. The `R.attr.selectableItemBackground` has a bit a different behavior which is the reason why I chose to use the other one. 

You can just add the code to your project if you need a different behavior and API 10 support

**Comment by munsuri** [comment]
@mikepenz thanks for pointing that out. I thought I could get away with some tweaks to support API 10 but there are many other things "breaking".

Do you have any suggestion or recommendation for Lists that support API level 10?
