### ISSUE TITLE
[Error] When ItemAdapter.Set() get lower item count then before

### ISSUE THREAD

**Issue by FabianTerhorst** [mikepenz/FastAdapter#17]
```
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{2e77778 position=3 id=-1, oldPos=3, pLpos:-1 scrap [attachedScrap] tmpDetached no parent}
  at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:4251)
  at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4382)
  at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4363)
  at android.support.v7.widget.LayoutState.next(LayoutState.java:86)
  at android.support.v7.widget.StaggeredGridLayoutManager.fill(StaggeredGridLayoutManager.java:1423)
  at android.support.v7.widget.StaggeredGridLayoutManager.onLayoutChildren(StaggeredGridLayoutManager.java:610)
  at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2864)
  at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3071)
  at android.view.View.layout(View.java:16636)
  at android.view.ViewGroup.layout(ViewGroup.java:5437)
  at android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1037)
  at android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:747)
  at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
  at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1156)
  at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:760)
  at android.view.View.layout(View.java:16636)
  at android.view.ViewGroup.layout(ViewGroup.java:5437)
  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
  at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
  at android.view.View.layout(View.java:16636)
  at android.view.ViewGroup.layout(ViewGroup.java:5437)
  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
  at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
  at android.view.View.layout(View.java:16636)
  at android.view.ViewGroup.layout(ViewGroup.java:5437)
  at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1043)
  at android.view.View.layout(View.java:16636)
  at android.view.ViewGroup.layout(ViewGroup.java:5437)
  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
  at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
  at android.view.View.layout(View.java:16636)
  at android.view.ViewGroup.layout(ViewGroup.java:5437)
  at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
  at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
  at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
  at android.view.View.layout(View.java:16636)
  at android.view.ViewGroup.layout(ViewGroup.java:5437)
  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
  at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
  at android.view.View.layout(View.java:16636)
  at android.view.ViewGroup.layout(ViewGroup.java:5437)
  at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
  at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
  at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
  at android.view.View.layout(View.java:16636)
  at android.view.ViewGroup.layout(ViewGroup.java:5437)
  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
  at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
  at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2678)
  at android.view.View.layout(View.java:16636)
  at android.view.ViewGroup.layout(ViewGroup.java:5437)
  at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2171)
  at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1931)
  at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
  at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
at android.view.Choreographer$CallbackRecord.run(Choreograph
```
```java
 mFastAdapter = new FastAdapter();
 mItemAdapter = new ItemAdapter();
 mList = (RecyclerView) rowView.findViewById(R.id.recyclerView);
 mList.setLayoutManager(Utils.getDefaultLayoutManager(getActivity()));
 mList.setAdapter(mItemAdapter.wrap(mFastAdapter));
mItemAdapter.set(mItems);//count 14

mItemAdapter.set(mItems);//count 13 and here it crashes
```

**Comment by mikepenz** [comment]
@FabianTerhorst that's how the RecyclerView adapter works. 

How have you removed the item?

In general you should call 
```java
itemAdapter.remove(int position);
```

This will not only remove the item at the given position, but it will also notify the adapter about the removed item so it can animate

**Comment by FabianTerhorst** [comment]
@mikepenz when im calling mItemAdapter.notifyDataSetChanged(); it doesn´t crashes too, but when the data comes from a api for example and you get 3 items and before you got 4 items, you couldn´t know that,

**Comment by mikepenz** [comment]
@FabianTerhorst then you should provide this via a new `List` and not by modifiying the previously set list

This works:
<img width="579" alt="bildschirmfoto 2016-01-04 um 17 47 41" src="https://cloud.githubusercontent.com/assets/1476232/12094844/4abf71ca-b30b-11e5-9d19-80e17cd71536.png">

**Comment by FabianTerhorst** [comment]
@mikepenz thanks, creating a new ArrayList works.

**Comment by mikepenz** [comment]
@FabianTerhorst to get a bit more into detail:

Yes it may work if we call `notifyDataSetChanged()`, but that's not true. If you set a list to the `ItemAdapter` you change all items of this adapter, but this one may isn't the only adapter providing items, and there are other adapters which also host items inside the `RecyclerView` as this is the case, we want to animate the change of items, so i call 
```java
notifyAdapterItemRangeChanged
``` 
and make sure the Adapter know how to correclty animate the changed items.

**Comment by drayan85** [comment]
Please refer the stackoverflow post

http://stackoverflow.com/questions/35653439/recycler-view-inconsistency-detected-invalid-view-holder-adapter-positionviewh

**Comment by alashow** [comment]
@drayan85 that solution is only changes name of the exception. After catching IOOB exception, another exception `Added View has RecyclerView as parent but view is not a real child. Unfiltered index:n` starts to throw.  I managed to fix it by wrapping set/add methods with `Handler.postDelayed`. But I still get `Scrapped or attached views may not be recycled. isScrap:false isAttached:true`, if I scroll down fast.

**Comment by oksett** [comment]
I had similiar issue, and also this solution has helped me, after I've added new item to my RV:
`recyclerView.getRecycledViewPool().clear();`
 `adapter.notifyDataSetChanged();`
