### ISSUE TITLE
AbstractMethodError

### ISSUE THREAD

**Issue by shuufi** [mikepenz/FastAdapter#197]
Wondering where went wrong. I'm using version 1.8.2 with extension 1.8.0. Following the example code from [the main page](https://github.com/mikepenz/FastAdapter)

```
09-12 07:01:24.549 2831-2831/io.peronda E/AndroidRuntime: FATAL EXCEPTION: main
                                                          Process: io.peronda, PID: 2831
                                                          java.lang.AbstractMethodError: abstract method "void com.mikepenz.fastadapter.IItem.bindView(android.support.v7.widget.RecyclerView$ViewHolder, java.util.List)"
                                                              at com.mikepenz.fastadapter.FastAdapter$OnBindViewHolderListenerImpl.onBindViewHolder(FastAdapter.java:1726)
                                                              at com.mikepenz.fastadapter.FastAdapter.onBindViewHolder(FastAdapter.java:528)
                                                              at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:5855)
                                                              at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5091)
                                                              at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4967)
                                                              at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2029)
                                                              at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1414)
                                                              at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1377)
                                                              at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:578)
                                                              at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3315)
                                                              at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3124)
                                                              at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3568)
                                                              at android.view.View.layout(View.java:15671)
                                                              at android.view.ViewGroup.layout(ViewGroup.java:5038)
                                                              at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1076)
                                                              at android.view.View.layout(View.java:15671)
                                                              at android.view.ViewGroup.layout(ViewGroup.java:5038)
                                                              at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1221)
                                                              at android.view.View.layout(View.java:15671)
                                                              at android.view.ViewGroup.layout(ViewGroup.java:5038)
                                                              at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                              at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                              at android.view.View.layout(View.java:15671)
                                                              at android.view.ViewGroup.layout(ViewGroup.java:5038)
                                                              at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
                                                              at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
                                                              at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
                                                              at android.view.View.layout(View.java:15671)
                                                              at android.view.ViewGroup.layout(ViewGroup.java:5038)
                                                              at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                              at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                              at android.view.View.layout(View.java:15671)
                                                              at android.view.ViewGroup.layout(ViewGroup.java:5038)
                                                              at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
                                                              at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
                                                              at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
                                                              at android.view.View.layout(View.java:15671)
                                                              at android.view.ViewGroup.layout(ViewGroup.java:5038)
                                                              at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                              at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                              at android.view.View.layout(View.java:15671)
                                                              at android.view.ViewGroup.layout(ViewGroup.java:5038)
                                                              at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2086)
                                                              at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1843)
                                                              at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
                                                              at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5885)
                                                              at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
                                                              at android.view.Choreographer.doCallbacks(Choreographer.java:580)
                                                              at android.view.Choreographer.doFrame(Choreographer.java:550)
                                                              at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
                                                              at android.os.Handler.handleCallback(Handler.java:739)
                                                              at android.os.Handler.dispatchMessage(Handler.java:95)
                                                              at android.os.Looper.loop(Looper.java:135)
                                                              at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                              at java.lang.reflect.Method.invoke(Method.java:372)
                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                          	at com.android.internal
```

**Caller from fragment**

```
/**
     * Initiliase recycler view
     */
    private fun initRecyclerView() {
        recyclerView.setHasFixedSize(true)
        val linearLayout = LinearLayoutManager(context)
        recyclerView.layoutManager = linearLayout
        if (recyclerView.adapter == null) {
            recyclerView.adapter = FastItemAdapter<VisitBySiteItem>()
        }
    }
```

**Model item implementing AbstractItem**

```
class VisitBySiteItem(private val site: Site, private val visit: Visit)
: AbstractItem<VisitBySiteItem, VisitBySiteItem.ViewHolder>()
{
    /**
     * Layout to be inflated
     */
    override fun getLayoutRes(): Int {
        return R.layout.fragment_operator_visit_by_site_list_item
    }

    /**
     * Parent container id
     */
    override fun getType(): Int {
        return R.id.VisitBySiteItemId
    }

    /**
     * On bind
     */
    override fun bindView(vh: ViewHolder?, payloads: MutableList<Any?>?) {
        super.bindView(vh, payloads)

        // Bind the data
        vh?.siteNameView?.text = this.site.name
        vh?.guardNameView?.text = this.visit.guard?.firstName
        vh?.timestampView?.text = this.visit.timestamp?.toString()
    }

    /**
     * View holder
     */
    class ViewHolder(private val view: View) : RecyclerView.ViewHolder(view)
    {
        var siteNameView: TextView? = null
        var guardNameView: TextView? = null
        var timestampView: TextView? = null

        init {
            siteNameView = view.findViewById(R.id.siteNameView) as TextView
            guardNameView = view.findViewById(R.id.guardNameView) as TextView
            timestampView = view.findViewById(R.id.timestampView) as TextView
        }
    }
}
```

**ids.xml**

```
<resources>
    <item name="VisitBySiteItemId" type="id" />
</resources>
```

**Comment by FabianTerhorst** [comment]
Maybe its because you are using kotlin and you are using MutableList?

**Comment by shuufi** [comment]
I'm not too sure myself. I've changed to `List<Any?>?` and removing the override method also didn't resolve this. I guess it's because of Kotlin?

**Comment by mikepenz** [comment]
@shuufi I am not sure but perhaps you also need the following with kotlin:
https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/items/SampleItem.java#L148
https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/items/SampleItem.java#L160

**Comment by shuufi** [comment]
I've git a try with implementing the factory but I got the same result, still crashing at this method `void com.mikepenz.fastadapter.IItem.bindView(android.support.v7.widget.RecyclerView$ViewHolder, java.util.List)`

[VisitByItem.kt](https://gist.github.com/shuufi/6368458b8ae207edcc17da4329a7d9b5).

If the library doesn't work with Kotlin yet, that's fine.

**Comment by mikepenz** [comment]
@shuufi I am not sure what a companion object is, but the `getFactory()` method should be overwritten from the `AbstractItem`
