### ISSUE TITLE
MopubFastItemAdapter is crashed

### ISSUE THREAD

**Issue by steventxc** [mikepenz/FastAdapter#211]
I found in the v1.8.2 and later, the `MopubFastItemAdapter` must commented the `onBindViewHolder(final RecyclerView.ViewHolder holder, int position)` method, if not , it would be crashed when I started the `MopubAdsSample`.

````
/**
     * fix the MopubAdapter not correctly overwriting the proper onBindViewHolder methods
     * @param holder   the viewHolder we bind the data on
     * @param position the global position
     */
    @Override
    public void onBindViewHolder(final RecyclerView.ViewHolder holder, int position) {
        super.onBindViewHolder(holder, position, Collections.EMPTY_LIST);
    }
````

 The log is :
 
```
FATAL EXCEPTION: main
Process: com.mikepenz.fastadapter.app, PID: 7538
java.lang.StackOverflowError
at com.mikepenz.fastadapter.app.adapters.MopubFastItemAdapter.onBindViewHolder(MopubFastItemAdapter.java:35) at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:5822)
at com.mikepenz.fastadapter.FastAdapter.onBindViewHolder(FastAdapter.java:527)
at com.mikepenz.fastadapter.app.adapters.MopubFastItemAdapter.onBindViewHolder(MopubFastItemAdapter.java:35)
at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:5822)
at com.mikepenz.fastadapter.FastAdapter.onBindViewHolder(FastAdapter.java:527)
at com.mikepenz.fastadapter.app.adapters.MopubFastItemAdapter.onBindViewHolder(MopubFastItemAdapter.java:35)
at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:5822)
at com.mikepenz.fastadapter.FastAdapter.onBindViewHolder(FastAdapter.java:527)
                                                                                
...........                                                                                

```

when I looked up the sources, I found the super method is slight difference

````
@Override
    public void onBindViewHolder(final RecyclerView.ViewHolder holder, int position) {
        if(mLegacyBindViewMode) {
            onBindViewHolder(holder, position, Collections.EMPTY_LIST);
        }
        //empty implementation we want the users to use the payloads too
    }
````
it was a condition there.

I don't know much about it, should I remove the method in my code ?

**Comment by mikepenz** [comment]
@steventxc please see here: https://github.com/mikepenz/FastAdapter/issues/181#issuecomment-243502324

This problem is caused because `Mopub` implemented their adapter not 100% correct
