### ISSUE TITLE
AbstractMethodError - IItem.unbindView

### ISSUE THREAD

**Issue by MFlisar** [mikepenz/FastAdapter#237]
**Happens in the DEV branch**

I'm getting this error:

	java.lang.AbstractMethodError: abstract method "void com.mikepenz.fastadapter.IItem.unbindView(android.support.v7.widget.RecyclerView$ViewHolder)"
		 at com.mikepenz.fastadapter.FastAdapter$OnBindViewHolderListenerImpl.unBindViewHolder(FastAdapter.java:1824)
		 at com.mikepenz.fastadapter.FastAdapter.onViewRecycled(FastAdapter.java:562)
		 at android.support.v7.widget.RecyclerView$Recycler.dispatchViewRecycled(RecyclerView.java:5525)
		 at android.support.v7.widget.RecyclerView$Recycler.addViewHolderToRecycledViewPool(RecyclerView.java:5290)
		 at android.support.v7.widget.RecyclerView$Recycler.recycleViewHolderInternal(RecyclerView.java:5273)
		 at android.support.v7.widget.RecyclerView.removeAnimatingView(RecyclerView.java:1198)
		 at android.support.v7.widget.RecyclerView$ItemAnimatorRestoreListener.onAnimationFinished(RecyclerView.java:10834)
		 at android.support.v7.widget.RecyclerView$ItemAnimator.dispatchAnimationFinished(RecyclerView.java:11334)
		 at android.support.v7.widget.SimpleItemAnimator.dispatchChangeFinished(SimpleItemAnimator.java:304)
		 at android.support.v7.widget.DefaultItemAnimator$7.onAnimationEnd(DefaultItemAnimator.java:363)
		 at android.support.v4.view.ViewPropertyAnimatorCompatJB$1.onAnimationEnd(ViewPropertyAnimatorCompatJB.java:47)
		 at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd(ViewPropertyAnimator.java:1114)
		 at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1239)
		 at android.animation.ValueAnimator$AnimationHandler.doAnimationFrame(ValueAnimator.java:766)
		 at android.animation.ValueAnimator$AnimationHandler$1.run(ValueAnimator.java:801)
		 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:920)
		 at android.view.Choreographer.doCallbacks(Choreographer.java:695)
		 at android.view.Choreographer.doFrame(Choreographer.java:628)
		 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:906)
		 at android.os.Handler.handleCallback(Handler.java:739)
		 at android.os.Handler.dispatchMessage(Handler.java:95)
		 at android.os.Looper.loop(Looper.java:158)
		 at android.app.ActivityThread.main(ActivityThread.java:7229)
		 at java.lang.reflect.Method.invoke(Native Method)
		 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
		 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
		 at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)

Any idea what could cause this?

**Comment by mikepenz** [comment]
@MFlisardo you use any other library like the `MaterialDrawer` or the `AboutLibraries`, do you include the module on your own, or do you use the latest snapshot?

**Comment by MFlisar** [comment]
I'm using both libraries and include the latest released versions there... I'm excluding the `FastAdapter` (and all other dependencies of your libraries) everywhere though:

    compile('com.mikepenz:aboutlibraries:5.8.1@aar') {
        transitive = true
        exclude group: 'com.mikepenz'
    }

     compile('com.mikepenz:materialdrawer:5.6.0@aar') {
        exclude group: 'com.mikepenz'
        transitive = true
    }

    // here I add the FastAdapter library
    compile project(':library')
    compile project(':library-extensions')

**Comment by mikepenz** [comment]
@MFlisar yes. But in this case it isn't that easy. As the v2.x will have some breaking changes which change the interface. So existing items have to be altered. The `MaterialDrawer` and the `AboutLibraries` both use `Item`s. 

I will have a look and release compatible snapshots.

**Comment by MFlisar** [comment]
The crash happens in a direct usage of the `FastAdapter` though not somewhere in a dependency... But this probably is the problem...

Thanks

**Comment by mikepenz** [comment]
@MFlisar if you update to the `5.7.0-SNAPSHOT` version of the `MaterialDrawer` it should work

**Comment by Rainer-Lang** [comment]
@mikepenz Is there an ETA for FastAdapter v2?

**Comment by MFlisar** [comment]
@Rainer-Lang 

You can always use jitpack.

Looks like following for the drawer for example:

    allprojects {
		repositories {
			maven { url "https://jitpack.io" }
		}
	}

    compile('com.github.mikepenz:MaterialDrawer:develop-SNAPSHOT') {
        exclude group: 'com.mikepenz'
        transitive = true
    }
