### ISSUE TITLE
Is it possible to add both headerAdapter and footerAdapter?

### ISSUE THREAD

**Issue by stonecold123** [mikepenz/FastAdapter#249]
I'm getting `java.lang.ClassCastException: com.item.HeaderView$ViewHolder cannot be cast to com.component.recycler.PagerFooterView$ViewHolder` when adding both headerAdapter and footerAdapter. There's no problem adding just either one of them. 

Is it possible to add both to fastAdapter?

Here's how I wrap the adapters:

````
recyclerView.setAdapter(headerAdapter.wrap(footerAdapter.wrap(itemAdapter.wrap(fastAdapter))));
````

````
class someClass{
    private FastAdapter<TagFastAdapter> fastAdapter;
    private HeaderAdapter<HeaderView> headerAdapter;
    private FooterAdapter<PagerFooterView> footerAdapter;

    @Override
    public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        TagItem data = parseBundleData();
        Context context = getContext();
        fastAdapter = new FastAdapter<TagFastAdapter>();
        fastAdapter.withPositionBasedStateManagement(false);

        RecyclerView recyclerView = (RecyclerView) view.findViewById(R.id.recycle_container);
        recyclerView.setLayoutManager(new LinearLayoutManager(context));
        headerAdapter = new HeaderAdapter<>();
        footerAdapter = new FooterAdapter<>();
        final GenericItemAdapter<TagItem, TagFastAdapter> itemAdapter =
                new GenericItemAdapter<>(TagFastAdapter.class,TagItem.class);
       

      recyclerView.setAdapter(headerAdapter.wrap(footerAdapter.wrap(itemAdapter.wrap(fastAdapter))));
        itemAdapter.addModel(data);
        headerAdapter.add(new HeaderView());
        footerAdapter.add(new PagerFooterView());
        fastAdapter.withSavedInstanceState(savedInstanceState);
        return view;

    }
}
````

````
Process: com.site, PID: 21237
java.lang.ClassCastException: com.item.HeaderView$ViewHolder cannot be cast to com.component.recycler.PagerFooterView$ViewHolder
at com.component.recycler.PagerFooterView.bindView(PagerFooterView.java:15)
at com.mikepenz.fastadapter.FastAdapter$OnBindViewHolderListenerImpl.onBindViewHolder(FastAdapter.java:1662)
at com.mikepenz.fastadapter.FastAdapter.onBindViewHolder(FastAdapter.java:496)
at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6062)
at com.mikepenz.fastadapter.AbstractAdapter.onBindViewHolder(AbstractAdapter.java:151)
at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6095)
at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5277)
at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5153)
at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2061)
at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1445)
at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1408)
at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:580)
at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3374)
at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:2901)
at android.view.View.measure(View.java:16772)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5139)
at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
....
````

**Comment by mikepenz** [comment]
@stonecold123 yes that's possible. you just have to make sure your `FastAdapter` has a parent type implemented by both types used in the `HeaderAdapter` and `FooterAdapter` (and `ItemAdapter`). So if those items are completely different you want to use `IItem` as type for the `FastAdapter`
