### ISSUE TITLE
java.lang.AbstractMethodError: abstract method not implemented

### ISSUE THREAD

**Issue by siper** [mikepenz/FastAdapter#256]
Hello, Im using material drawer and fast adapter in my project, when i published app into google play, on test step I have this error on 8 devices. On Android 5.1+ works good. 
```
java.lang.AbstractMethodError: abstract method not implemented
 	at com.mikepenz.materialdrawer.model.AbstractDrawerItem.unbindView(AbstractDrawerItem.java)
 	at com.mikepenz.fastadapter.FastAdapter$OnBindViewHolderListenerImpl.unBindViewHolder(FastAdapter.java:1847)
 	at com.mikepenz.fastadapter.FastAdapter.onViewRecycled(FastAdapter.java:582)
 	at android.support.v7.widget.RecyclerView$Recycler.dispatchViewRecycled(RecyclerView.java:5726)
 	at android.support.v7.widget.RecyclerView$Recycler.addViewHolderToRecycledViewPool(RecyclerView.java:5491)
 	at android.support.v7.widget.RecyclerView$Recycler.recycleCachedViewAt(RecyclerView.java:5406)
 	at android.support.v7.widget.RecyclerView$Recycler.recycleViewHolderInternal(RecyclerView.java:5451)
 	at android.support.v7.widget.RecyclerView$Recycler.quickRecycleScrapView(RecyclerView.java:5506)
 	at android.support.v7.widget.RecyclerView$LayoutManager.removeAndRecycleScrapInt(RecyclerView.java:8023)
 	at android.support.v7.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:3447)
 	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3194)
 	at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3627)
 	at android.view.View.layout(View.java:14969)
 	at android.view.ViewGroup.layout(ViewGroup.java:4656)
 	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055)
 	at android.view.View.layout(View.java:14969)
 	at android.view.ViewGroup.layout(ViewGroup.java:4656)
 	at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1217)
 	at android.view.View.layout(View.java:14969)
 	at android.view.ViewGroup.layout(ViewGroup.java:4656)
 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
 	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
 	at android.view.View.layout(View.java:14969)
 	at android.view.ViewGroup.layout(ViewGroup.java:4656)
 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
 	at android.view.View.layout(View.java:14969)
 	at android.view.ViewGroup.layout(ViewGroup.java:4656)
 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
 	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
 	at android.view.View.layout(View.java:14969)
 	at android.view.ViewGroup.layout(ViewGroup.java:4656)
 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
 	at android.view.View.layout(View.java:14969)
 	at android.view.ViewGroup.layout(ViewGroup.java:4656)
 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
 	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
 	at android.view.View.layout(View.java:14969)
 	at android.view.ViewGroup.layout(ViewGroup.java:4656)
 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2142)
 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1860)
 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1076)
 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5905)
 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:807)
 	at android.view.Choreographer.doCallbacks(Choreographer.java:601)
 	at android.view.Choreographer.doFrame(Choreographer.java:562)
 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:791)
 	at android.os.Handler.handleCallback(Handler.java:733)
 	at android.os.Handler.dispatchMessage(Handler.java:95)
 	at android.os.Looper.loop(Looper.java:157)
 	at android.app.ActivityThread.main(ActivityThread.java:5633)
 	at java.lang.reflect.Method.invokeNative(Native Method)
 	at java.lang.reflect.Method.invoke(Method.java:515)
 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:896)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:712)
```

**Comment by mikepenz** [comment]
@siper do you use the latest version of those libraries? If you have fastadapter 2.x but an old version of the MaterialDrawer you will run into problems

**Comment by siper** [comment]
Ok update libs helps me, thank you.
