### ISSUE TITLE
[Error] Proguard

### ISSUE THREAD

**Issue by rmoreira0** [mikepenz/FastAdapter#27]
Hi!

When i run the application without proguard, everything works but if i use proguard, the application crash and give me this error

````
java.lang.RuntimeException: something really bad happened. if this happens more often, head over to GitHub and read how to switch to the ViewHolderFactory
                                                                                 at com.mikepenz.fastadapter.items.AbstractItem.getViewHolder(AbstractItem.java:226)
                                                                                 at com.mikepenz.fastadapter.items.AbstractItem.getViewHolder(AbstractItem.java:184)
                                                                                 at com.mikepenz.fastadapter.FastAdapter$OnCreateViewHolderListenerImpl.onPreCreateViewHolder(FastAdapter.java:1087)
                                                                                 at com.mikepenz.fastadapter.FastAdapter.onCreateViewHolder(FastAdapter.java:264)
                                                                                 at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:5228)
                                                                                 at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4453)
                                                                                 at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4363)
                                                                                 at android.support.v7.widget.bt.a(LinearLayoutManager.java:1961)
                                                                                 at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1370)
                                                                                 at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1333)
                                                                                 at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:562)
                                                                                 at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2900)
                                                                                 at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3071)
                                                                                 at android.view.View.layout(View.java:15596)
                                                                                 at android.view.ViewGroup.layout(ViewGroup.java:4966)
                                                                                 at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
                                                                                 at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
                                                                                 at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
                                                                                 at android.view.View.layout(View.java:15596)
                                                                                 at android.view.ViewGroup.layout(ViewGroup.java:4966)
                                                                                 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
                                                                                 at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
                                                                                 at android.view.View.layout(View.java:15596)
                                                                                 at android.view.ViewGroup.layout(ViewGroup.java:4966)
                                                                                 at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1627)
                                                                                 at android.view.View.layout(View.java:15596)
                                                                                 at android.view.ViewGroup.layout(ViewGroup.java:4966)
                                                                                 at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1076)
                                                                                 at android.view.View.layout(View.java:15596)
                                                                                 at android.view.ViewGroup.layout(ViewGroup.java:4966)
                                                                                 at android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1037)
                                                                                 at android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:747)
                                                                                 at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:761)
                                                                                 at android.view.View.layout(View.java:15596)
                                                                                 at android.view.ViewGroup.layout(ViewGroup.java:4966)
                                                                                 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
                                                                                 at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
                                                                                 at android.view.View.layout(View.java:15596)
                                                                                 at android.view.ViewGroup.layout(ViewGroup.java:4966)
                                                                                 at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
                                                                                 at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
                                                                                 at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
                                                                                 at android.view.View.layout(View.java:15596)
                                                                                 at android.view.ViewGroup.layout(ViewGroup.java:4966)
                                                                                 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
                                                                                 at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
                                                                                 at android.view.View.layout(View.java:15596)
                                                                                 at android.view.ViewGroup.layout(ViewGroup.java:4966)
                                                                                 at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
                                                                                 at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
                                                                                 at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
                                                                                 at android.view.View.layout(View.java:15596)
                                                                                 at android.view.ViewGroup.layout(ViewGroup.java:4966)
                                                                                 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
                                                                                 at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
                                                                                 at android.view.View.layout(View.java:15596)
                                                                                 at android.view.ViewGroup.layout(ViewGroup.java:4966)
                                                                             	at android.view.Vie

````

How can I solve this?

Thanks

**Comment by mattiasbe** [comment]
As per the error message, implement the simple viewholder factory to return an instance of the viewholder, for example as in the example app (lower half of this file):
https://github.com/mikepenz/FastAdapter/blob/master/app/src/main/java/com/mikepenz/fastadapter/app/generic/GenericIconItem.java

**Comment by rmoreira0** [comment]
It works! Thank you

**Comment by mikepenz** [comment]
@mattiasbe thank you for answering :)
