### ISSUE TITLE
Fatal on backPressed com.mikepenz.fastadapter.IItem.unbindView

### ISSUE THREAD

**Issue by Demuss** [mikepenz/FastAdapter#270]
I got fatal on back pressed from activity to activity
Everything loads fine, items are shown

```
java.lang.AbstractMethodError: abstract method "void com.mikepenz.fastadapter.IItem.unbindView (android.support.v7.widget.RecyclerView$ViewHolder)"
    at com.mikepenz.fastadapter.FastAdapter$OnBindViewHolderListenerImpl.unBindViewHolder(FastAdapter.java:1849)
    at com.mikepenz.fastadapter.FastAdapter.onViewRecycled(FastAdapter.java:584)
    at android.support.v7.widget.RecyclerView$Recycler.dispatchViewRecycled(RecyclerView.java:5731)
    at android.support.v7.widget.RecyclerView$Recycler.addViewHolderToRecycledViewPool(RecyclerView.java:5496)
    at android.support.v7.widget.RecyclerView$Recycler.recycleViewHolderInternal(RecyclerView.java:5479)
    at android.support.v7.widget.RecyclerView.removeAnimatingView(RecyclerView.java:1242)
    at android.support.v7.widget.RecyclerView$ItemAnimatorRestoreListener.onAnimationFinished(RecyclerView.java:11156)
    at android.support.v7.widget.RecyclerView$ItemAnimator.dispatchAnimationFinished(RecyclerView.java:11656)
    at android.support.v7.widget.SimpleItemAnimator.dispatchChangeFinished(SimpleItemAnimator.java:304)
    at android.support.v7.widget.DefaultItemAnimator$7.onAnimationEnd(DefaultItemAnimator.java:363)
    at android.support.v4.view.ViewPropertyAnimatorCompatJB$1.onAnimationEnd(ViewPropertyAnimatorCompatJB.java:47)
    at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd(ViewPropertyAnimator.java:1135)
    at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1239)
    at android.animation.ValueAnimator$AnimationHandler.doAnimationFrame(ValueAnimator.java:766)
    at android.animation.ValueAnimator$AnimationHandler$1.run(ValueAnimator.java:801)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:894)
    at android.view.Choreographer.doCallbacks(Choreographer.java:696)
    at android.view.Choreographer.doFrame(Choreographer.java:628)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:880)
    at android.os.Handler.handleCallback(Handler.java:815)
    at android.os.Handler.dispatchMessage(Handler.java:104)
    at android.os.Looper.loop(Looper.java:207)
    at android.app.ActivityThread.main(ActivityThread.java:5728)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
```

**Comment by mikepenz** [comment]
@Demuss which version are you on?

**Comment by mikepenz** [comment]
Seems like you have a version missmatch. Do you use also the `MaterialDrawer` or `AboutLibraries`?

**Comment by Demuss** [comment]
version 2.1.0 and yeah I use materialDrawer 5.6.0

**Comment by mikepenz** [comment]
Please read the migration guide. 

2.1.0 requires material drawer 5.8.0

**Comment by Demuss** [comment]
Thank you, didn't notice when viewed guide. I'll try it later
