### ISSUE TITLE
onBind is not called

### ISSUE THREAD

**Issue by alashow** [mikepenz/FastAdapter#300]
After upgrading from `1.2.5-6` to `2.1.0-5` (yeah, that's a long jump) my item's `bindView` method is not being called, so my views are [empty](https://dl2.pushbulletusercontent.com/3CJyo5fLHDSwkLgro9vIkZZ9lxKCURts/Screenshot_20161224-203301.png) now.

My item object: https://gist.github.com/alashow/7aa42f7211c7290f9d889a0685daeaf2

The only things I added/updated are:
`onBind(holder)` -> `onBind(holder, payloads)`
implemented `unbindView(holder)`
click listener helpers to `ClickEventHooker`.

After debugging, I noticed that my `bindVIew` method is not being called.

**Comment by alashow** [comment]
Also, I had extremely annoying bugs with `Insistency detected. Invalid view holder adapter positionViewHolder ...` and `Added View has RecyclerView as parent but view is not a real child`. Which I solved by wrapping `fastAdapter.add*|set*` methods with a delayed `Handler`.

**Comment by mikepenz** [comment]
@alashow do you set a `LayoutManager` to the RV? 

Which version of the support libs do you use? It may be a result from the updates to the `RecyclerView` rather than the adapter.

**Comment by alashow** [comment]
Yes, I use `LinearLayoutManger`.

My support lib version is `25.1.0`. I upgraded support libs version before. It was working with `1.2.5-6`.

**Comment by alashow** [comment]
I was using https://github.com/yasevich/endless-recycler-view for my recyclerView. Turns out, new versions of FastAdapter is not compatible with it. I changed it to normal RecyclerView, and it worked as intended. Anyways I was going to switch FastAdapter's version of infinite/endless loading.

My bad.

Thank you for the awesome library!

**Comment by mikepenz** [comment]
@alashow very interesting, shouldn't be an incompatiblity as the fastadapter fullfills the requirements a normal rv adapter has

**Comment by alashow** [comment]
But I'm sure that the problem was with the custom rv. As soon as I changed it to normal rv, the problem was solved.

**Comment by alashow** [comment]
@mikepenz kinda unrelated but do you know why every time I add `ProgressItem` to FooterAdapter, I get this warning exception:
```
Cannot call this method in a scroll callback. Scroll callbacks might be run during a measure & layout pass where you cannot change the RecyclerView data. Any method call that might change the structure of the RecyclerView or the adapter contents should be postponed to the next frame.
			java.lang.IllegalStateException: 
			at android.support.v7.widget.RecyclerView.assertNotInLayoutOrScroll(RecyclerView.java:2526)
			at android.support.v7.widget.RecyclerView$RecyclerViewDataObserver.onItemRangeInserted(RecyclerView.java:4874)
			at android.support.v7.widget.RecyclerView$AdapterDataObservable.notifyItemRangeInserted(RecyclerView.java:11094)
			at android.support.v7.widget.RecyclerView$Adapter.notifyItemRangeInserted(RecyclerView.java:6702)
			at com.mikepenz.fastadapter.FastAdapter.notifyAdapterItemRangeInserted(FastAdapter.java:1546)
			at com.mikepenz.fastadapter.adapters.ItemAdapter.add(ItemAdapter.java:352)
			at com.mikepenz.fastadapter.adapters.ItemAdapter.add(ItemAdapter.java:335)
			at tm.veriloft.sowgat.ui.fragment.product.ProductListFragment.toggleFooterLoading(ProductListFragment.java:521)
			at tm.veriloft.sowgat.ui.fragment.product.ProductListFragment.access$700(ProductListFragment.java:62)
			at tm.veriloft.sowgat.ui.fragment.product.ProductListFragment$OnLoadListener.onStart(ProductListFragment.java:543)
			at tm.veriloft.sowgat.ui.fragment.product.ProductListFragment$5.onStart(ProductListFragment.java:421)
			at tm.veriloft.sowgat.rest.Summon.<init>(Summon.java:18)
			at tm.veriloft.sowgat.ui.fragment.product.ProductListFragment$5.<init>(ProductListFragment.java:0)
			at tm.veriloft.sowgat.ui.fragment.product.ProductListFragment.loadItems(ProductListFragment.java:418)
			at tm.veriloft.sowgat.ui.fragment.product.ProductListFragment.access$400(ProductListFragment.java:62)
			at tm.veriloft.sowgat.ui.fragment.product.ProductListFragment$2.onLoadMore(ProductListFragment.java:185)
			at com.mikepenz.fastadapter_extensions.scroll.EndlessRecyclerOnScrollListener.onScrolled(EndlessRecyclerOnScrollListener.java:116)
			at android.support.v7.widget.RecyclerView.dispatchOnScrolled(RecyclerView.java:4541)
			at android.support.v7.widget.RecyclerView.scrollByInternal(RecyclerView.java:1698)
			at android.support.v7.widget.RecyclerView.onTouchEvent(RecyclerView.java:2827)
			at android.view.View.dispatchTouchEvent(View.java:10023)
			at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2626)
			at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2307)
			at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
			at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
			at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
			at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
			at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
			at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
			at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
			at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
			at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
			at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
			at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
			at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
			at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
			at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
			at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
			at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
			at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
			at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
			at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
			at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
			at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:413)
			12-26 03:52:06.588 17924-17924/tm.veriloft.sowgat.debug W/RecyclerView:     at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1808)
			at android.app.Activity.dispatchTouchEvent(Activity.java:3061)
			at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
			at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
			at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:375)
			at android.view.View.dispatchPointerEvent(View.java:10243)
			at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4438)
			at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4306)
			at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
			at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3906)
			at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3872)
			at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3999)
			at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3880)
			at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4056)
			at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
			at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3906)
			at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3872)
			at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3880)
			at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
			at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6246)
			at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6220)
			at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6181)
			at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6349)
			at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
			at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
			at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
			at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6320)
			at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6372)
			at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
			at android.view.Choreographer.doCallbacks(Choreographer.java:686)
			at android.view.Choreographer.doFrame(Choreographer.java:615)
			at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
			at android.os.Handler.handleCallback(Handler.java:751)
			at android.os.Handler.dispatchMessage(Handler.java:95)
			at android.os.Looper.loop(Looper.java:154)
			at android.app.ActivityThread.main(ActivityThread.java:6119)
			at java.lang.reflect.Method.invoke(Native Method)
			at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
			at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```
