### ISSUE TITLE
NPE when referencing a view from within ClickEventHook via getViewHolder()

### ISSUE THREAD

**Issue by Ben-Reily** [mikepenz/FastAdapter#306]
Hi, I've got an item with a `ClickEventHook` defined in it. The goal is to handle clicks the same way for 2 different views in the item. So I use `onBindMany` and return a list of 2 views: 
1) the item itself (its root view I guess, the whole body)
2) `ImageButton `somewhere in the hierarchy
It goes fine when I click the item itself (i.e. when body view is clicked). No exceptions or anything, click is handled properly.

The problem occurs in `ExpandClickEvent `only when clicking on this `ImageButton`. When I try to access any of the widgets (`expandableContent`, button or any other) via `item.getViewHolder(v)` i get a `NullPointerException`. In the provided code fragment the exception is thrown when it gets to the line with `  expandContent.setVisibility(item.isExpanded ? View.GONE : View.VISIBLE)`. But it happens when accessing any view in the ViewHolder.

Is it some library-specific bug or am I doing it wrong with handling view clicks? 

StackTrace of this:

```
FATAL EXCEPTION: main
  Process: com.artyom.mobile PID: 3432
    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.constraint.ConstraintLayout.setVisibility(int)' on a null object reference
    at com.mobile.adapters.VacancyAdapterItem$ExpandClickEvent.onClick(VacancyAdapterItem.java:429)
    at com.mobile.adapters.VacancyAdapterItem$ExpandClickEvent.onClick(VacancyAdapterItem.java:421)
    at com.mikepenz.fastadapter.helpers.ClickListenerHelper$1.onClick(ClickListenerHelper.java:118)
    at com.rey.material.widget.RippleManager.dispatchClickEvent(RippleManager.java:95)
    at com.rey.material.widget.RippleManager.onClick(RippleManager.java:90)
    at android.view.View.performClick(View.java:5697)
    at android.view.View$PerformClick.run(View.java:22526)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:158)
    at android.app.ActivityThread.main(ActivityThread.java:7225)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

```java
    public class VacancyAdapterItem extends AbstractItem<VacancyAdapterItem, VacancyAdapterItem.ViewHolder> {

    private static final ViewHolderFactory<? extends ViewHolder> FACTORY = new ItemFactory();

    private VacancyModel vacancy;

    public boolean isExpanded = false;


    public VacancyAdapterItem(VacancyModel model) {
        this.vacancy = model;
    }

    @Override
    public int getType() {
        return R.id.card_vacancy;
    }

    @Override
    public int getLayoutRes() {
        return R.layout.item_vacancy;
    }


    @Override
    public void bindView(ViewHolder holder, List<Object> payloads) {
        super.bindView(holder, payloads);
    }


    @Override
    public void unbindView(ViewHolder holder) {
        super.unbindView(holder);
    }

    private static class ItemFactory implements ViewHolderFactory<ViewHolder> {
        public ViewHolder create(View view) {
            return new ViewHolder(view);
        }
    }

    @Override
    public ViewHolderFactory<? extends ViewHolder> getFactory() {
        return FACTORY;
    }

    public static class ViewHolder extends RecyclerView.ViewHolder {
        public View view;

        public ConstraintLayout expandableContent;
        public Button btnApply;
        public ImageButton ivExpandCollapse;

        public ViewHolder(View view) {
            super(view);
            this.view = view;

            expandableContent = (ConstraintLayout) view.findViewById(R.id.vac_expandable_content);
            btnApply = (Button) view.findViewById(R.id.btn_vac_apply);
            ivExpandCollapse = (ImageButton) view.findViewById(R.id.iv_vac_expand_arrow);
        }
    }

    public static class ExpandClickEvent extends ClickEventHook<VacancyAdapterItem> {
        @Nullable
        @Override
        public List<View> onBindMany(@NonNull RecyclerView.ViewHolder viewHolder) {
            if (viewHolder instanceof VacancyAdapterItem.ViewHolder) {
                List<View> list = new ArrayList<>();
                list.add(((ViewHolder) viewHolder).view);
                list.add(((ViewHolder) viewHolder).ivExpandCollapse);
                return list;
            }
            return null;
        }


        @Override
        public void onClick(View v, int position, FastAdapter<VacancyAdapterItem> fastAdapter, VacancyAdapterItem item) {
            ConstraintLayout expandContent = item.getViewHolder(v).expandableContent;
            expandContent.setVisibility(item.isExpanded ? View.GONE : View.VISIBLE);
            item.isExpanded = !item.isExpanded;

            if (item.isExpanded) {
                item.getViewHolder(v).ivExpandCollapse.setRotation(-180);
            } else {
                item.getViewHolder(v).ivExpandCollapse.setRotation(0);
            }
        }
    }
}
```

**Comment by mikepenz** [comment]
@Ben-Reily are you sure
```java
expandableContent = (ConstraintLayout) view.findViewById(R.id.vac_expandable_content);
```
exists? 

Can you debug into the `ViewHolder` constructor and check if it gets set?
