### ISSUE TITLE
Crash on API 19 when using different Objects that extend AbstractItem to fill FastAdapter

### ISSUE THREAD

**Issue by dyckster** [mikepenz/FastAdapter#319]
Recently I wanted to test how my app works on API 19 and I found out it crashes on screens that use FastItemAdaper with the type of IItem.  Right now, what I am doing, is filling this adapter with different items that extend AbstractItem, on API>21 it worked ok, but on 19 it doesnt. 

Exceptions that I get:

`E/UncaughtException: android.view.InflateException: Binary XML file line #57: Error inflating class ImageView
                         at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:714)
                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:756)
                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:759)
                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:759)
                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:759)
                         at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
                         at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                         at com.mikepenz.fastadapter.items.AbstractItem.getViewHolder(AbstractItem.java:234)
                         at com.mikepenz.fastadapter.FastAdapter$OnCreateViewHolderListenerImpl.onPreCreateViewHolder(FastAdapter.java:1690)
                         at com.mikepenz.fastadapter.FastAdapter.onCreateViewHolder(FastAdapter.java:396)
                         at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6290)
                         at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5478)
                         at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5363)
                         at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5359)
                         at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2141)
                         at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1525)
                         at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1488)
                         at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:585)
                         at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3506)
                         at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3254)
                         at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3767)
                         at android.view.View.layout(View.java:14817)
                         at android.view.ViewGroup.layout(ViewGroup.java:4631)
                         at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
                         at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
                         at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
                         at android.view.View.layout(View.java:14817)
                         at android.view.ViewGroup.layout(ViewGroup.java:4631)
                         at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1193)
                         at android.view.View.layout(View.java:14817)
                         at android.view.ViewGroup.layout(ViewGroup.java:4631)
                         at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                         at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                         at android.view.View.layout(View.java:14817)
                         at android.view.ViewGroup.layout(ViewGroup.java:4631)
                         at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
                         at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
                         at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
                         at android.view.View.layout(View.java:14817)
                         at android.view.ViewGroup.layout(ViewGroup.java:4631)
                         at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                         at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                         at android.view.View.layout(View.java:14817)
                         at android.view.ViewGroup.layout(ViewGroup.java:4631)
                         at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
                         at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
                         at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
                         at android.view.View.layout(View.java:14817)
                         at android.view.ViewGroup.layout(ViewGroup.java:4631)
                         at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                         at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                         at android.view.View.layout(View.java:14817)
                         at android.view.ViewGroup.layout(ViewGroup.java:4631)
                         at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:1987)
                         at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1744)
                         at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1000)
                         at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5670)
                     	at android.view.Choreog`
 ~~
`E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.DyDo.yury.rollertutor, PID: 10795
                  android.view.InflateException: Binary XML file line #57: Error inflating class ImageView
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:714)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:756)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:759)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:759)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:759)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                      at com.mikepenz.fastadapter.items.AbstractItem.getViewHolder(AbstractItem.java:234)
                      at com.mikepenz.fastadapter.FastAdapter$OnCreateViewHolderListenerImpl.onPreCreateViewHolder(FastAdapter.java:1690)
                      at com.mikepenz.fastadapter.FastAdapter.onCreateViewHolder(FastAdapter.java:396)
                      at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6290)
                      at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5478)
                      at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5363)
                      at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5359)
                      at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2141)
                      at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1525)
                      at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1488)
                      at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:585)
                      at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3506)
                      at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3254)
                      at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3767)
                      at android.view.View.layout(View.java:14817)
                      at android.view.ViewGroup.layout(ViewGroup.java:4631)
                      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
                      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
                      at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
                      at android.view.View.layout(View.java:14817)
                      at android.view.ViewGroup.layout(ViewGroup.java:4631)
                      at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1193)
                      at android.view.View.layout(View.java:14817)
                      at android.view.ViewGroup.layout(ViewGroup.java:4631)
                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                      at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                      at android.view.View.layout(View.java:14817)
                      at android.view.ViewGroup.layout(ViewGroup.java:4631)
                      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
                      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
                      at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
                      at android.view.View.layout(View.java:14817)
                      at android.view.ViewGroup.layout(ViewGroup.java:4631)
                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                      at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                      at android.view.View.layout(View.java:14817)
                      at android.view.ViewGroup.layout(ViewGroup.java:4631)
                      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
                      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
                      at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
                      at android.view.View.layout(View.java:14817)
                      at android.view.ViewGroup.layout(ViewGroup.java:4631)
                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                      at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                      at android.view.View.layout(View.java:14817)
                      at android.view.ViewGroup.layout(ViewGroup.java:4631)
                      at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:1987)
                      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1744)
                      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1000)
                  	at android.view.ViewRootImpl$Trave`

**Comment by FabianTerhorst** [comment]
Could you post the item and adapter creation code?

**Comment by dyckster** [comment]
@FabianTerhorst Sure.
Here, if thats what you need
```
private FastItemAdapter<IItem> itemsAdapter;
private void setupRecyclerView() {
        itemsAdapter = new FastItemAdapter<>();
        leadersRecycler.setLayoutManager(new LinearLayoutManager(getActivity()));
        leadersRecycler.addItemDecoration(new VerticalSpaceItemDecoration(Utils.dip(getActivity(), 8)));
        itemsAdapter.add(new AddItem());
```

```
private void addItemToAdapter(RideLeader leader) {
        itemsAdapter.add(0, new LeaderItem(leader));
        itemsAdapter.notifyDataSetChanged();
    }
```

**Comment by mikepenz** [comment]
@dyckster I think you may use some function in your layout which is not supported on API 19.

**Comment by dyckster** [comment]
@mikepenz Yep, you are right, sorry for my stupidity :)
