### ISSUE TITLE
deleting searched (filtered) item bug

### ISSUE THREAD

**Issue by or-dvir** [mikepenz/FastAdapter#342]
hi

i implemented a search (filter) but if i delete an item while search\filter is active, when i exit search mode the item is back on the list

**Comment by mikepenz** [comment]
@or-dvir this happens because the filter keeps the list of item inside a temp list. As during filtering the main list is switched out. 

It may require some more logic to get filtering + allowing to delete / add items

**Comment by mikepenz** [comment]
@or-dvir if you are deleting an item and you also currently filtered, you have to use the internal provided methods for adding deleting of the Filter

https://github.com/mikepenz/FastAdapter/blob/develop/library-core/src/main/java/com/mikepenz/fastadapter/adapters/ItemAdapter.java#L675

**Comment by or-dvir** [comment]
@mikepenz i have been trying to find a way for this (delete item while filtered) to work for several days now  but no success.

will you please provide guidelines and/or sample code on how this can be achieved?

**Comment by mikepenz** [comment]
@or-dvir are you able to include the source of the library in your project. I have made some chances a while ago which might help here:

https://github.com/mikepenz/FastAdapter/commit/318ded9e29453a190e8f5643bb47358fdc341437

**Comment by or-dvir** [comment]
@mikepenz as far as i can tell it doesn't fix the issue

**Comment by mikepenz** [comment]
hmmm :/. Did you use the provided methods from the filter instead the ones from the Adapter?

**Comment by or-dvir** [comment]
@mikepenz can you please tell me which method are you referring to specifically (and from which class)? the link you posted is not for the filter, but for ItemAdapter

**Comment by mikepenz** [comment]
@or-dvir those available on the `ItemFilter` which is available from the `ItemAdapter`

`((ItemFilter)itemAdapter.getItemFilter()).*`

**Comment by or-dvir** [comment]
@mikepenz  i tried doing this in commitRemove():

((ItemAdapter.ItemFilter)mAdapter.getItemFilter()).remove(positions.iterator().next());
but this is what i get when closing the search view:

```
FATAL EXCEPTION: main
                                                 Process: or_dvir.hotmail.com.fastadapter_test, PID: 5951
                                                 java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 12(offset:50).state:13
                                                     at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5504)
                                                     at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5440)
                                                     at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5436)
                                                     at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2224)
                                                     at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1551)
                                                     at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
                                                     at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
                                                     at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3534)
                                                     at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3310)
                                                     at android.support.v7.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:1648)
                                                     at android.support.v7.widget.RecyclerView$1.run(RecyclerView.java:343)
                                                     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                     at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                     at android.view.Choreographer.doFrame(Choreographer.java:603)
                                                     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                     at android.os.Looper.loop(Looper.java:148)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5551)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
```

**Comment by mikepenz** [comment]
The `RecyclerView` can be quite unhappy if different things change items at the same moment. Shit shouldn't be done. 

Perhaps the best is. to reset the filter. remove the item. and reapply the filter?

**Comment by mikepenz** [comment]
or you handle the filtering on your side, as it seems you have a special scenario where more logic is required and the default filtering doesn't do everything for you

**Comment by mikepenz** [comment]
Please report back to get this reopened :)

**Comment by or-dvir** [comment]
@mikepenz thanks.
i need more time to come up with a solution for this, so in the meantime i have moved on to other things.

**Comment by TheMaxCoder** [comment]
This is how I achieved this
Set a filter listener `withItemFilterListener` and cache the results in a field variable
Now when you want to remove an item:
First get the item position from results by iterating over it
then use `itemAdapter.itemFilter.remove(position)`
It will remove the item from the filtered list as well as the original list.

I don't know if this solution is perfect but @mikepenz  if we can achieve this in a better way please mention.

Thanks
