### ISSUE TITLE
Attempt to invoke virtual method 'void android.content.res.TypedArray.recycle()' on a null object reference

### ISSUE THREAD

**Issue by JakeWoki** [mikepenz/FastAdapter#385]
``` Java
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.content.res.TypedArray.recycle()' on a null object reference
                                                                                at com.turingtechnologies.materialscrollbar.MaterialScrollBar.generalSetup(MaterialScrollBar.java:246)
                                                                                at com.turingtechnologies.materialscrollbar.MaterialScrollBar.<init>(MaterialScrollBar.java:111)
                                                                                at com.turingtechnologies.materialscrollbar.DragScrollBar.<init>(DragScrollBar.java:42)
                                                                                at com.mikepenz.fastadapter.app.GenericItemActivity.onCreate(GenericItemActivity.java:69)
                                                                                at android.app.Activity.performCreate(Activity.java:6102)
                                                                                at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2403)
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2512) 
                                                                                at android.app.ActivityThread.access$1200(ActivityThread.java:165) 
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1373) 
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                at android.os.Looper.loop(Looper.java:135) 
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5593) 
                                                                                at java.lang.reflect.Method.invoke(Native Method) 
                                                                                at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:967) 
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762) 
```

**Comment by FabianTerhorst** [comment]
Take a look at the sample to see how the ```MaterialScrollBar```is implemented there.

**Comment by mikepenz** [comment]
The bug is a `MaterialScrollBar` crash. please refer to this libs doc.
