### ISSUE TITLE
Resources$NotFoundException: Resource ID #0x0

### ISSUE THREAD

**Issue by or-dvir** [mikepenz/FastAdapter#388]
hi
all of a sudden this morning i started getting this exception.
last time i worked on my app (last week) everything was perfectly fine, and now this...
any ideas?
i am using fast adapter version 2.1.5.
i tried the newest version too and still happening.
i tried cleaning and project.

*note: a similar issue happened to me when using material drawer, however that was due to my theme not inheriting from appcompat. this time though, i am inheriting from appcompat

```java
android.content.res.Resources$NotFoundException: Resource ID #0x0
                                                                                    at android.content.res.Resources.getValue(Resources.java:1401)
                                                                                    at android.content.res.Resources.loadXmlResourceParser(Resources.java:2882)
                                                                                    at android.content.res.Resources.getLayout(Resources.java:1215)
                                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:421)
                                                                                    at com.mikepenz.fastadapter.items.AbstractItem.getViewHolder(AbstractItem.java:239)
                                                                                    at com.mikepenz.fastadapter.FastAdapter$OnCreateViewHolderListenerImpl.onPreCreateViewHolder(FastAdapter.java:1786)
                                                                                    at com.mikepenz.fastadapter.FastAdapter.onCreateViewHolder(FastAdapter.java:440)
                                                                                    at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6367)
                                                                                    at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5555)
                                                                                    at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5440)
                                                                                    at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5436)
                                                                                    at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2224)
                                                                                    at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1551)
                                                                                    at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
                                                                                    at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
                                                                                    at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3583)
                                                                                    at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3312)
                                                                                    at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3844)
                                                                                    at android.view.View.layout(View.java:16694)
                                                                                    at android.view.ViewGroup.layout(ViewGroup.java:5481)
                                                                                    at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
                                                                                    at android.view.View.layout(View.java:16694)
                                                                                    at android.view.ViewGroup.layout(ViewGroup.java:5481)
                                                                                    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                                    at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                                    at android.view.View.layout(View.java:16694)
                                                                                    at android.view.ViewGroup.layout(ViewGroup.java:5481)
                                                                                    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
                                                                                    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
                                                                                    at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
                                                                                    at android.view.View.layout(View.java:16694)
                                                                                    at android.view.ViewGroup.layout(ViewGroup.java:5481)
                                                                                    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                                    at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                                    at android.view.View.layout(View.java:16694)
                                                                                    at android.view.ViewGroup.layout(ViewGroup.java:5481)
                                                                                    at android.support.v7.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:437)
                                                                                    at android.view.View.layout(View.java:16694)
                                                                                    at android.view.ViewGroup.layout(ViewGroup.java:5481)
                                                                                    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                                    at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                                    at android.view.View.layout(View.java:16694)
                                                                                    at android.view.ViewGroup.layout(ViewGroup.java:5481)
                                                                                    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
                                                                                    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
                                                                                    at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
                                                                                    at android.view.View.layout(View.java:16694)
                                                                                    at android.view.ViewGroup.layout(ViewGroup.java:5481)
                                                                                    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                                    at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                                    at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2697)
                                                                                    at android.view.View.layout(View.java:16694)
                                                                                    at android.view.ViewGroup.layout(ViewGroup.java:5481)
                                                                                    at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2228)
                                                                                    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1981)
                                                                                    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1140)
                                                                                	at android.view.ViewRootImpl$TraversalRunnable.run
```

**Comment by FabianTerhorst** [comment]
The error i happening on the layout inflate and should not be related to this library. You'll get this error anywhere you inflate this layout.

**Comment by mikepenz** [comment]
As @FabianTerhorst already noted, this is not related to the FastAdapter library
