### ISSUE TITLE
Footer adapter example RecylerView error

### ISSUE THREAD

**Issue by engineers-bojan** [mikepenz/FastAdapter#408]
I've implemented the footer sample code and i am getting complaints from the RecylerView: " Cannot call this method in a scroll callback. Scroll callbacks mightbe run during a measure & layout pass where you cannot change theRecyclerView data. Any method call that might change the structureof the RecyclerView or the adapter contents should be postponed tothe next frame."

```
java.lang.IllegalStateException: 
                                                                         at android.support.v7.widget.RecyclerView.assertNotInLayoutOrScroll(RecyclerView.java:2581)
                                                                         at android.support.v7.widget.RecyclerView$RecyclerViewDataObserver.onItemRangeInserted(RecyclerView.java:4951)
                                                                         at android.support.v7.widget.RecyclerView$AdapterDataObservable.notifyItemRangeInserted(RecyclerView.java:11383)
                                                                         at android.support.v7.widget.RecyclerView$Adapter.notifyItemRangeInserted(RecyclerView.java:6779)
                                                                         at com.mikepenz.fastadapter.FastAdapter.notifyAdapterItemRangeInserted(FastAdapter.java:1588)
                                                                         at com.mikepenz.fastadapter.adapters.ItemAdapter.add(ItemAdapter.java:366)
                                                                         at com.mikepenz.fastadapter.adapters.ItemAdapter.add(ItemAdapter.java:349)
                                                                         at ***.***.***.AbstractMainListFragment$1.onLoadMore(AbstractMainListFragment.java:47)
                                                                         at com.mikepenz.fastadapter_extensions.scroll.EndlessRecyclerOnScrollListener.onScrolled(EndlessRecyclerOnScrollListener.java:122)
                                                                         at android.support.v7.widget.RecyclerView.dispatchOnScrolled(RecyclerView.java:4618)
                                                                         at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:4776)
                                                                         at android.view.Choreographer$CallbackRecord.run(Choreographer.java:873)
                                                                         at android.view.Choreographer.doCallbacks(Choreographer.java:676)
                                                                         at android.view.Choreographer.doFrame(Choreographer.java:603)
                                                                         at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:859)
                                                                         at android.os.Handler.handleCallback(Handler.java:739)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                         at android.os.Looper.loop(Looper.java:168)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5845)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)
```

The Load more works as expected, but this is something that should be addressed in the sample?

The relevant code that triggers the error:  

```java
recyclerView.addOnScrollListener(new EndlessRecyclerOnScrollListener(footerAdapter) {
            @Override
            public void onLoadMore(final int currentPage) {
                footerAdapter.clear();
                footerAdapter.add(new ProgressItem().withEnabled(false));
});
```

Edit:  Just to note, wrapping the adapter clear and add methods in a Handler/Runnable eliminates the issue as it postpones the operation after onScroll has finished in the recyclerview,.

**Comment by mikepenz** [comment]
@engineers-bojan "wrapping the adapter clear and add methods in a Handler/Runnable" is the proper solution as also noted by the error message

**Comment by mikepenz** [comment]
Does the crash occur in the sample? If yes please open a PR

**Comment by engineers-bojan** [comment]
Not sure about the actual sample, just copied the relevant code parts in a project i am testing but probably happens there too. (i'll test it later and PR if i manage to get some time)

**Comment by mikepenz** [comment]
Thank you

**Comment by mikepenz** [comment]
Please report back. closing for now
