### ISSUE TITLE
FastAdapter.registerTypeInstance() on a null object reference

### ISSUE THREAD

**Issue by judemanutd** [mikepenz/FastAdapter#466]
I am using [https://github.com/afollestad/material-dialogs](url) to generate a custom list dialog.

My model class

    public final class OverflowMenuItem {

    private int image;
    private String text;

    public OverflowMenuItem(int image, String text) {
        this.image = image;
        this.text = text;
    }

    public int getImage() {
        return image;
    }

    public void setImage(int image) {
        this.image = image;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }
    }

My GenericAbstractItem Class

    public final class GenericOverflowItem extends GenericAbstractItem<OverflowMenuItem, 
      GenericOverflowItem, OverflowItem_ViewHolder> {

    public GenericOverflowItem(OverflowMenuItem overflowMenuItem) {
        super(overflowMenuItem);
    }

    @Override
    public OverflowItem_ViewHolder getViewHolder(View v) {
        return new OverflowItem_ViewHolder(v);
    }

    @Override
    public int getType() {
        return R.id.fastadapter_overflow_localnews;
    }

    @Override
    public int getLayoutRes() {
        return R.layout.item_overflow_localnews;
    }

    @Override
    public void bindView(OverflowItem_ViewHolder holder, List<Object> payloads) {
        super.bindView(holder, payloads);

        OverflowMenuItem item = getModel();

        holder.getImage().setImageResource(item.getImage());
        holder.getText().setText(item.getText());
    }

    @Override
    public void unbindView(OverflowItem_ViewHolder holder) {
        super.unbindView(holder);
        holder.getImage().setImageDrawable(null);
        holder.getText().setText(null);
    }
    }

The part where i create the adapter

    fastAdapter.withEventHook(new ClickEventHook<GenericLocalNewsItem>() {

            @Nullable
            @Override
            public View onBind(@android.support.annotation.NonNull RecyclerView.ViewHolder viewHolder) 
            {
                if (viewHolder instanceof LocalNewsItem_ViewHolder) {
                    return ((LocalNewsItem_ViewHolder) viewHolder).getOverflow();
                }
                return super.onBind(viewHolder);
            }

            @Override
            public void onClick(View v, int position, FastAdapter<GenericLocalNewsItem> fastAdapter, 
                      GenericLocalNewsItem item) {
                List<OverflowMenuItem> overflowItems = new ArrayList<>();
                overflowItems.add(new OverflowMenuItem(R.drawable.ic_account_circle_black_24dp, "Text 1"));
                overflowItems.add(new OverflowMenuItem(R.drawable.ic_more_vert_black_24dp, "Text 2"));

                final FastAdapter<GenericOverflowItem> overflowItemFastAdapter = new FastAdapter<>();
                overflowItemFastAdapter.withSelectable(true);
                final GenericItemAdapter<OverflowMenuItem, GenericOverflowItem> adapter = new 
                 GenericItemAdapter<>(GenericOverflowItem::new);
                adapter.addModel(overflowItems);
                final LinearLayoutManager layoutManager = new LinearLayoutManager(getContext());
                layoutManager.setOrientation(LinearLayoutManager.VERTICAL);
                MaterialDialog overflow = new MaterialDialog.Builder(getContext())
                        .adapter(adapter.wrap(overflowItemFastAdapter), layoutManager)
                        .build();

                overflow.show();

            }
        });

I get the following crash log

    E/UncaughtException: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mikepenz.fastadapter.FastAdapter.registerTypeInstance(com.mikepenz.fastadapter.IItem)' on a null object reference
                                                                      at com.mikepenz.fastadapter.AbstractAdapter.mapPossibleType(AbstractAdapter.java:244)
                                                                      at com.mikepenz.fastadapter.AbstractAdapter.mapPossibleTypes(AbstractAdapter.java:233)
                                                                      at com.mikepenz.fastadapter.adapters.ItemAdapter.add(ItemAdapter.java:347)
                                                                      at com.mikepenz.fastadapter.adapters.GenericItemAdapter.addModel(GenericItemAdapter.java:81)
                                                                      at com.user.NewsFragment$3.onClick(NewsFragment.java:245)
                                                                      at com.user.NewsFragment$3.onClick(NewsFragment.java:225)
                                                                      at com.mikepenz.fastadapter.utils.EventHookUtil$1.onClick(EventHookUtil.java:72)
                                                                      at android.view.View.performClick(View.java:5207)
                                                                      at android.view.View$PerformClick.run(View.java:21177)
                                                                      at android.os.Handler.handleCallback(Handler.java:742)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                      at android.os.Looper.loop(Looper.java:154)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5529)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)

    E/AndroidRuntime: FATAL EXCEPTION: main
                                                               Process: com.user, PID: 2440
                                                               java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mikepenz.fastadapter.FastAdapter.registerTypeInstance(com.mikepenz.fastadapter.IItem)' on a null object reference
                                                                   at com.mikepenz.fastadapter.AbstractAdapter.mapPossibleType(AbstractAdapter.java:244)
                                                                   at com.mikepenz.fastadapter.AbstractAdapter.mapPossibleTypes(AbstractAdapter.java:233)
                                                                   at com.mikepenz.fastadapter.adapters.ItemAdapter.add(ItemAdapter.java:347)
                                                                   at com.mikepenz.fastadapter.adapters.GenericItemAdapter.addModel(GenericItemAdapter.java:81)
                                                                   at octave.politico.NewsFragment$3.onClick(NewsFragment.java:245)
                                                                   at octave.politico.NewsFragment$3.onClick(NewsFragment.java:225)
                                                                   at com.mikepenz.fastadapter.utils.EventHookUtil$1.onClick(EventHookUtil.java:72)
                                                                   at android.view.View.performClick(View.java:5207)
                                                                   at android.view.View$PerformClick.run(View.java:21177)
                                                                   at android.os.Handler.handleCallback(Handler.java:742)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                   at android.os.Looper.loop(Looper.java:154)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5529)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)

Have i missed initializing something?

**Comment by mikepenz** [comment]
@judemanutd I do not see any code on how you set the adapter, how you wrap the `ItemAdapter` for the `FastAdapter`, ...

**Comment by judemanutd** [comment]
@mikepenz  I did that in the builder of the dialog itself in the following lines

    MaterialDialog overflow = new MaterialDialog.Builder(getContext())
                    .adapter(adapter.wrap(overflowItemFastAdapter), layoutManager)
                    .build();

**Comment by mikepenz** [comment]
https://github.com/mikepenz/FastAdapter/blob/develop/library-core/src/main/java/com/mikepenz/fastadapter/AbstractAdapter.java#L244

The crash only happens if you use an adapter which was not wrapped. please make sure that this was done.

**Comment by judemanutd** [comment]
@mikepenz  found the error the line `adapter.addModel(overflowItems);` needed to come after the adapter was wrapped so putting it after `MaterialDialog overflow = new MaterialDialog.Builder(getContext())
                .adapter(adapter.wrap(overflowItemFastAdapter), layoutManager)
                .build();` worked.
