### ISSUE TITLE
[3.0.0.7] IndexOutOfBoundsException when remove(0) in 2nd ItemAdapter

### ISSUE THREAD

**Issue by sosite** [mikepenz/FastAdapter#491]
When i try to `remove(0)` in 2nd ItemAdapter `FastAdapter.with(1ndItemAdapter, 2ndITemAdapter);` then I received below error:

```
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 0(offset:-1).state:32
    at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5512)
    at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5448)
    at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5444)
    at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2224)
    at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1551)
    at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
    at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:605)
    at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3551)
    at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3327)
    at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3867)
    ...
```

Also trying to `move()` item often brings unexpected behavior.

Below code should do what I describe above:
```java
IItemAdapter firstAdapter = new ItemAdapter();
IItemAdapter secondAdapter = new ItemAdapter();
FastAdapter.with(firstAdapter, secondAdapter);

firstAdapter.add(new DummyItem());
secondAdapter.add(new DummyItem());

new Handler().postDelayed(() -> secondAdapter.remove(0), 5000);
```

**Comment by mikepenz** [comment]
@sosite thank you very much, we will have a look into it.

**Comment by mikepenz** [comment]
Ok the crash is happening because you use the relative position (so "0" is relative to the `secondAdapter`) As the javadoc already writes. This method expects the global position to be used. 

```java
secondAdapter.remove(secondAdapter.getGlobalPosition(0));
```

adapter's come with a handy helper to give you the `globalPosition`
