### ISSUE TITLE
IndexOutOfBoundsException

### ISSUE THREAD

**Issue by PDDStudio** [mikepenz/FastAdapter#50]
```
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 0(offset:2).state:2
  at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4405)
  at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4363)
  at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1961)
  at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1370)
  at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1333)
  at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:562)
  at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2900)
  at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3071)
  at android.view.View.layout(View.java:16636)
  at android.view.ViewGroup.layout(ViewGroup.java:5437)
  at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:584)
  at android.view.View.layout(View.java:16636)
  at android.view.ViewGroup.layout(ViewGroup.java:5437)
  at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
  at android.view.View.layout(View.java:16636)
  at android.view.ViewGroup.layout(ViewGroup.java:5437)
  at android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1037)
  at android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:747)
  at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
  at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1156)
  at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:760)
  at android.view.View.layout(View.java:16636)
  at android.view.ViewGroup.layout(ViewGroup.java:5437)
  at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1043)
  at android.view.View.layout(View.java:16636)
  at android.view.ViewGroup.layout(ViewGroup.java:5437)
  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
  at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
  at android.view.View.layout(View.java:16636)
  at android.view.ViewGroup.layout(ViewGroup.java:5437)
  at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
  at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
  at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
  at android.view.View.layout(View.java:16636)
  at android.view.ViewGroup.layout(ViewGroup.java:5437)
  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
  at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
  at android.view.View.layout(View.java:16636)
  at android.view.ViewGroup.layout(ViewGroup.java:5437)
  at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
  at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
  at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
  at android.view.View.layout(View.java:16636)
  at android.view.ViewGroup.layout(ViewGroup.java:5437)
  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
  at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
  at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2678)
  at android.view.View.layout(View.java:16636)
  at android.view.ViewGroup.layout(ViewGroup.java:5437)
  at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2171)
  at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1931)
  at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
  at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
  at android.view.Choreographer.doCallbacks(Choreographer.java:670)
  at android.view.Choreographer.doFrame(Choreographer.java:606)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreogra
```

Crash occurs when re-creating the [related Fragment](https://github.com/PDDStudio/NetworkUtils/blob/master/app/src/main/java/com/pddstudio/networkingdemo/fragments/ArpInfoFragment.java) - might have something to do with notifyItemRemoved(position)

**Comment by mikepenz** [comment]
@PDDStudio which version do you use?

**Comment by PDDStudio** [comment]
@mikepenz I'm using `1.0.6`

**Comment by mikepenz** [comment]
@PDDStudio could you please add some more detailed steps to reproduce? Or even a sample app?
It is really hard to reproduce such exceptions because they are thrown by the `RecyclerView` `LayoutManager`

**Comment by PDDStudio** [comment]
@mikepenz you can check out the repository from the link I've posted and build the sample app. The application starts without any problems but by switching to another fragment via the navigation drawer and navigating back to 'ARP information' the crash occurs.

**Comment by mikepenz** [comment]
@PDDStudio can you please try again with v1.1.0

**Comment by PDDStudio** [comment]
@mikepenz sure, will do so asap and report back!

**Comment by PDDStudio** [comment]
@mikepenz issue is still present with `1.1.1`

**Comment by mikepenz** [comment]
@PDDStudio doesn't seem to be a `FastAdapter` issue, but a general `RecyclerView` issue. As far as I have tracked down the issue it seems when recreating the view, it has a different `Thread` as the first time, so it gets into an inconsistent state. 

I solved it by doing:
```
new Handler().postDelayed(new Runnable() {
            @Override
            public void run() {
                fetchArpInfo();
            }
}, 0);
```

But I do not know what exactly is causing this..
I also found this bug report: https://code.google.com/p/android/issues/detail?id=158046

**Comment by PDDStudio** [comment]
@mikepenz thanks for pointing out, but unfortunately your workaround isn't working at all, same issue as before.

**Comment by mikepenz** [comment]
@PDDStudio I downloaded your source and run it. It worked.

**Comment by PDDStudio** [comment]
@mikepenz am I adding it at the correct place? Otherwise could you create a pull request please? :smile:
