### ISSUE TITLE
the problem about Use filter and select

### ISSUE THREAD

**Issue by fly7632785** [mikepenz/FastAdapter#550]
Hi, @mikepenz 
This is a great library I have seen.
Now, I'm using filter and select functions at same time
But I discover that when selecting some items, the filter function is not working.
And I debug it.
When I have selected some items, then filter, the withFilterPredicated's filter is not invoked.
Here my codes:
```
fastItemAdapter.getItemFilter().withFilterPredicate(new IItemAdapter.Predicate<D0_3_FriendChooseItem>() {
            @Override
            public boolean filter(D0_3_FriendChooseItem item, CharSequence constraint) {
                return !item.getFriendWalkStatusModel().getNickNm().contains(String.valueOf(constraint));
            }
        });
```
```
   public static class CheckBoxClickEvent extends ClickEventHook<D0_3_FriendChooseItem> {
        @Override
        public View onBind(@NonNull RecyclerView.ViewHolder viewHolder) {
            if (viewHolder instanceof D0_3_FriendChooseItem.ViewHolder) {
                return ((ViewHolder) viewHolder).binding.getRoot();
            }
            return null;
        }

        @Override
        public void onClick(View v, int position, FastAdapter<D0_3_FriendChooseItem> fastAdapter, D0_3_FriendChooseItem item) {
            fastAdapter.toggleSelection(position);
        }
    }
```
and Exception:
```
An exception occured during performFiltering()!
                                                                          android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
                                                                              at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:6855)
                                                                              at android.view.ViewRootImpl.invalidateChildInParent(ViewRootImpl.java:1075)
                                                                              at android.view.ViewGroup.invalidateChild(ViewGroup.java:5242)
                                                                              at android.view.View.invalidateInternal(View.java:13573)
                                                                              at android.view.View.invalidate(View.java:13537)
                                                                              at android.view.View.invalidate(View.java:13521)
                                                                              at android.widget.TextView.checkForRelayout(TextView.java:7342)
                                                                              at android.widget.TextView.setText(TextView.java:4475)
                                                                              at android.widget.TextView.setText(TextView.java:4332)
                                                                              at android.widget.TextView.setText(TextView.java:4307)
                                                                              at jp.co.taknet.hss.android.ui.fragment.D0_3_FriendListFragment.lambda$initRecyclerView$1$D0_3_FriendListFragment(D0_3_FriendListFragment.java:77)
                                                                              at jp.co.taknet.hss.android.ui.fragment.D0_3_FriendListFragment$$Lambda$1.onSelectionChanged(Unknown Source)
                                                                              at com.mikepenz.fastadapter.FastAdapter.deselect(FastAdapter.java:1302)
                                                                              at com.mikepenz.fastadapter.FastAdapter.deselect(FastAdapter.java:1267)
                                                                              at com.mikepenz.fastadapter.FastAdapter.deselect(FastAdapter.java:1213)
                                                                              at com.mikepenz.fastadapter.adapters.ItemFilter.performFiltering(ItemFilter.java:68)
                                                                              at android.widget.Filter$RequestHandler.handleMessage(Filter.java:234)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                              at android.os.Looper.loop(Looper.java:154)
                                                                              at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by fly7632785** [comment]
and I debug, figure it out 
```
  @Override
    public FilterResults performFiltering(CharSequence constraint) {
        FilterResults results = new FilterResults();

        //return nothing
        if (mOriginalItems == null && (constraint == null || constraint.length() == 0)) {
            return results;
        }

        //we can not filter on expanded or selected items, because the remembered positions will change
        if (mItemAdapter.getFastAdapter().isPositionBasedStateManagement()) {
            mItemAdapter.getFastAdapter().deselect();
        }
        mItemAdapter.getFastAdapter().collapse(false);
```

so we can't filter selected items? right?

**Comment by fly7632785** [comment]
is there any way to user them at same time ?
I just want to filter all items, not the selected items

**Comment by fly7632785** [comment]
I think it's not reliable to manage a set of position,
So in my own custom Recycler's adapter, I just manage a set of the model's id or something which is different from others. And achieve it.

**Comment by mikepenz** [comment]
@fly7632785 as far as I've read this sounds like an issue which I will fix in the next update. 

Sorry for the inconvenience.

**Comment by fly7632785** [comment]
Never mind ,and thank you very much

**Comment by mikepenz** [comment]
The next version will fix the issues with the "clever"-viewholder and the selection and filtering
