### ISSUE TITLE
Cannot call this method in a scroll callback...

### ISSUE THREAD

**Issue by Tarik02** [mikepenz/FastAdapter#552]
```
11-01 22:26:16.551 5436-5436/com.agropostavka.agropostavka W/RecyclerView: Cannot call this method in a scroll callback. Scroll callbacks mightbe run during a measure & layout pass where you cannot change theRecyclerView data. Any method call that might change the structureof the RecyclerView or the adapter contents should be postponed tothe next frame.
                                                                           java.lang.IllegalStateException:  android.support.v7.widget.RecyclerView{e241ec2 VFED.V... .F....ID 0,0-640,844 #7f080050 app:id/fragment_list_recycler_view}, adapter:com.mikepenz.fastadapter.FastAdapter@2cc64d3, layout:android.support.v7.widget.LinearLayoutManager@5f16810, context:com.agropostavka.agropostavka.activity.FragmentActivity@dba9958
                                                                               at android.support.v7.widget.RecyclerView.assertNotInLayoutOrScroll(RecyclerView.java:2673)
                                                                               at android.support.v7.widget.RecyclerView$RecyclerViewDataObserver.onItemRangeRemoved(RecyclerView.java:5082)
                                                                               at android.support.v7.widget.RecyclerView$AdapterDataObservable.notifyItemRangeRemoved(RecyclerView.java:11574)
                                                                               at android.support.v7.widget.RecyclerView$Adapter.notifyItemRangeRemoved(RecyclerView.java:6939)
                                                                               at com.mikepenz.fastadapter.FastAdapter.notifyAdapterItemRangeRemoved(FastAdapter.java:1175)
                                                                               at com.mikepenz.fastadapter.adapters.ModelAdapter.clear(ModelAdapter.java:560)
                                                                               at com.agropostavka.agropostavka.fragments.ListFragment.loadNextPage(ListFragment.kt:162)
                                                                               at com.agropostavka.agropostavka.fragments.ListFragment.access$loadNextPage(ListFragment.kt:36)
                                                                               at com.agropostavka.agropostavka.fragments.ListFragment$onViewCreated$$inlined$apply$lambda$6.onLoadMore(ListFragment.kt:137)
                                                                               at com.mikepenz.fastadapter_extensions.scroll.EndlessRecyclerOnScrollListener.onScrolled(EndlessRecyclerOnScrollListener.java:130)
                                                                               at android.support.v7.widget.RecyclerView.dispatchOnScrolled(RecyclerView.java:4722)
                                                                               at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:4891)
                                                                               at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
                                                                               at android.view.Choreographer.doCallbacks(Choreographer.java:723)
                                                                               at android.view.Choreographer.doFrame(Choreographer.java:655)
                                                                               at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
                                                                               at android.os.Handler.handleCallback(Handler.java:789)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                               at android.os.Looper.loop(Looper.java:164)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

Here's the code that i use for pagination(endless scrolling)(It's kotlin code):
```kotlin
			val scrollListener = object : EndlessRecyclerOnScrollListener(footerAdapter) {
				override fun onLoadMore(currentPage: Int) {
					loadNextPage()
				}
			}
			addOnScrollListener(scrollListener)
```
```kotlin
	private fun loadNextPage() {
		if (...some condition...) {
			footerAdapter.clear() // <--- this line is also in the stacktrace
			footerAdapter.add(NoMoreItemsItem())
		}
	}
```

So, in my opinion there are a solution: call onLoadMore only when user doesn't scroll(onScrollStateChanged)

**Comment by mikepenz** [comment]
@Tarik02 just use a handler and postpone the call to the next frame as mentioned in the trace:

```java
handler.post(new Runnable() {
                        @Override
                        public void run() {
                            footerAdapter.clear();
                            footerAdapter.add(new ProgressItem().withEnabled(false).withIdentifier(Long.MAX_VALUE - 1));
                        }
                    });
```

**Comment by soonsam123** [comment]
Thanks! It works perfectly 👍
