### ISSUE TITLE
Spinner item in recyclerview cause error

### ISSUE THREAD

**Issue by edi233** [mikepenz/FastAdapter#584]
I create item with spinner:

```
import android.content.Context
import android.support.v7.widget.RecyclerView
import android.view.View
import android.widget.ArrayAdapter
import android.widget.Spinner
import com.mikepenz.fastadapter.items.AbstractItem
import kotlinx.android.synthetic.main.item_select.view.*
import pl.skillforce.formsandroid.R

class ItemSelect constructor(val text: String, val options: List<String>) : AbstractItem<ItemSelect, ItemSelect.ViewHolder>() {


    override fun getType(): Int {
        return R.id.itemSpinner
    }

    override fun getLayoutRes(): Int {
        return R.layout.item_select
    }

    override fun bindView(holder: ViewHolder, payloads: MutableList<Any>?) {
        super.bindView(holder, payloads)
        val spinnerAdapter = ArrayAdapter<String>(holder.context, android.R.layout.simple_spinner_item)
        spinnerAdapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item)
        spinnerAdapter.addAll(options)

        holder.spinner.adapter = spinnerAdapter

        holder.spinner.setOnItemClickListener { _, view, _, _ -> }

    }

    override fun unbindView(holder: ViewHolder) {
        super.unbindView(holder)

    }

    override fun getViewHolder(v: View): ViewHolder {
        return ViewHolder(v)
    }

    class ViewHolder(view: View) : RecyclerView.ViewHolder(view) {
        val spinner: Spinner = view.itemSpinner
        val context: Context = view.context
    }
}

```
and add this item to my adapter: 
```
private val adapter = FastItemAdapter<IItem<*, *>>()
adapter.add(ItemSelect(text, options))
```
when I try to run activity I get error: 
```
java.lang.RuntimeException: Don't call setOnClickListener for an AdapterView. You probably want setOnItemClickListener instead
                                                                              at android.widget.AdapterView.setOnClickListener(AdapterView.java:1181)
                                                                              at com.mikepenz.fastadapter.utils.EventHookUtil.attachToView(EventHookUtil.java:58)
                                                                              at com.mikepenz.fastadapter.FastAdapter.onCreateViewHolder(FastAdapter.java:661)
                                                                              at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6488)
                                                                              at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5675)
                                                                              at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5558)
                                                                              at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5554)
                                                                              at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2229)
                                                                              at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1556)
                                                                              at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1516)
                                                                              at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:608)
                                                                              at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3694)
                                                                              at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3411)
                                                                              at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3963)
                                                                              at android.view.View.layout(View.java:18874)
                                                                              at android.view.ViewGroup.layout(ViewGroup.java:5954)
                                                                              at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                              at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1730)
                                                                              at android.widget.LinearLayout.onLayout(LinearLayout.java:1496)
                                                                              at android.view.View.layout(View.java:18874)
                                                                              at android.view.ViewGroup.layout(ViewGroup.java:5954)
                                                                              at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                              at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                              at android.view.View.layout(View.java:18874)
                                                                              at android.view.ViewGroup.layout(ViewGroup.java:5954)
                                                                              at android.support.v7.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:443)
                                                                              at android.view.View.layout(View.java:18874)
                                                                              at android.view.ViewGroup.layout(ViewGroup.java:5954)
                                                                              at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                              at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                              at android.view.View.layout(View.java:18874)
                                                                              at android.view.ViewGroup.layout(ViewGroup.java:5954)
                                                                              at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                              at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                              at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                              at android.view.View.layout(View.java:18874)
                                                                              at android.view.ViewGroup.layout(ViewGroup.java:5954)
                                                                              at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                              at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                              at com.android.internal.policy.DecorView.onLayout(DecorView.java:910)
                                                                              at android.view.View.layout(View.java:18874)
                                                                              at android.view.ViewGroup.layout(ViewGroup.java:5954)
                                                                              at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2697)
                                                                              at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2413)
                                                                              at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1550)
                                                                              at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7190)
                                                                              at android.view.Choreographer$CallbackRecord.run(Choreographer.java:959)
                                                                              at android.view.Choreographer.doCallbacks(Choreographer.java:734)
                                                                              at android.view.Choreographer.doFrame(Choreographer.java:670)
                                                                              at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:945)
                                                                              at android.os.Handler.handleCallback(Handler.java:751)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                              at android.os.Looper.loop(Looper.java:154)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:6776)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
12-05 14:26:46.098 6748-6748/pl.skillforce.formsandroid E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
```

**Comment by FabianTerhorst** [comment]
The viewholder view gets an click listener setted automatically. You should make sure your adapter view isnt the item root view.

**Comment by edi233** [comment]
works perfect. Thank you!

**Comment by Abdurrahmanjun** [comment]
sorry to followup this issue, can any one point me how to? because putting fastAdapter.withAttachDefaultListeners(false) at onclick under clickeventhook class doesnt help. what doyou mean "make sure your adapter view isnt the item root view."
