### ISSUE TITLE
FastAdapter.with NPE

### ISSUE THREAD

**Issue by AllanWang** [mikepenz/FastAdapter#591]
Code:
```java
ItemAdapter<ColorPickerIItem> headerAdapter = new ItemAdapter<>();
headerAdapter.add(new ColorPickerIItem());

List<IAdapter> adapters = new ArrayList<>();
adapters.add(headerAdapter);
adapters.add(adapter.getItemAdapter());
setAdapter(FastAdapter.with(adapters));
//        setAdapter(adapter);

```

Calling `setAdapter(FastAdapter.with(adapters));` fails, but `setAdapter(adapter)` works.
(This also works if I use `headerAdapter` directly).

Log:

```
java.lang.NullPointerException: Attempt to invoke interface method 'android.support.v7.widget.RecyclerView$ViewHolder com.mikepenz.fastadapter.IItem.getViewHolder(android.view.ViewGroup)' on a null object reference
                                         at com.mikepenz.fastadapter.listeners.OnCreateViewHolderListenerImpl.onPreCreateViewHolder(OnCreateViewHolderListenerImpl.java:23)
                                         at com.mikepenz.fastadapter.FastAdapter.onCreateViewHolder(FastAdapter.java:654)
                                         at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6519)
                                         at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5706)
                                         at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5589)
                                         at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5585)
                                         at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2231)
                                         at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1558)
                                         at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1518)
                                         at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:610)
                                         at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3719)
                                         at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3436)
                                         at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3988)
                                         at android.view.View.layout(View.java:17641)
                                         at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                         at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                         at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                         at android.view.View.layout(View.java:17641)
                                         at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                         at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                         at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                         at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                         at android.view.View.layout(View.java:17641)
                                         at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                         at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                         at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                         at android.view.View.layout(View.java:17641)
                                         at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                         at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                         at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                         at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                         at android.view.View.layout(View.java:17641)
                                         at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                         at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                         at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                         at android.view.View.layout(View.java:17641)
                                         at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                         at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                         at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                         at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                         at android.view.View.layout(View.java:17641)
                                         at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                         at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                         at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                         at com.android.internal.policy.DecorView.onLayout(DecorView.java:731)
                                         at android.view.View.layout(View.java:17641)
                                         at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                         at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2346)
                                         at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2068)
                                         at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
                                         at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6344)
                                         at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
                                         at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                         at android.view.Choreographer.doFrame(Choreographer.java:621)
12-23 21:32:01.454 E/AndroidRuntime:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                                         at android.os.Handler.handleCallback(Handler.java:751)
                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                         at android.os.Looper.loop(Looper.java:154)
                                         at android.app.ActivityThread.main(ActivityThread.java:6236)
                                         at java.lang.reflect.Method.invoke(Native Method)
                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
```

FastAdapter: 3.0.4
Support Libs: 27.0.2 (same as FastAdapter)

More info:
* This worked before with pre 3.0.
* I've also used `FastAdapter.with` before with other libraries, so I'm not sure what the issue is.
* `adapter` is a global `FastItemAdapter`
* This class extends `RecyclerView`
* The layout manager is set

**Comment by FabianTerhorst** [comment]
Can you remove the comments when there are unrelated to the issue.

**Comment by AllanWang** [comment]
```java
        FastAdapter<IItem> main = FastAdapter.with(Arrays.asList(headerAdapter.getItemAdapter(), adapter.getItemAdapter()));
        main.registerTypeInstance(new ColorPickerIItem());
        main.registerTypeInstance(new ShowcaseDraggableItem("", 0));
        setAdapter(main);
```

This is my suggestion, given that the item type is returning null.
I'm not sure how `FastAdapter` typically registers type instances, but maybe it is missing it in `FastAdapter.with`?

**Comment by FabianTerhorst** [comment]
Returns getType of your items an constant?

**Comment by AllanWang** [comment]
Yes. It is enforced that it returns an id res

**Comment by AllanWang** [comment]
Sample:

```java
public class ColorPickerIItem extends AbstractItem<ColorPickerIItem, ColorPickerIItem.ViewHolder> {

    @Override
    public ViewHolder getViewHolder(View v) {
        return new ViewHolder(v);
    }

    @Override
    public int getType() {
        return R.id.iitem_color_picker;
    }

    @Override
    public int getLayoutRes() {
        return R.layout.iitem_color_picker;
    }

    static class ViewHolder extends RecyclerView.ViewHolder {

        final AnimatedColorPicker picker;

        ViewHolder(View itemView) {
            super(itemView);
            picker = itemView.findViewById(R.id.color_picker);
            if (itemView.getContext() instanceof AnimatedColorPicker.ColorPickerListener)
                picker.setColorListener((AnimatedColorPicker.ColorPickerListener) itemView.getContext());
            else
                Timber.d("ColorPickerIItem has no bound color listener");
        }
    }
}
```

**Comment by FabianTerhorst** [comment]
You could theoretically return any int, not just an resource. Just wanted to be sure it doesnt change on runtime.

**Comment by FabianTerhorst** [comment]
You shouldnt use an FastItemAdapter to just return the item adapter from it and assign it to another FastAdapter that will loose the TypeInstanceCache.

**Comment by AllanWang** [comment]
@FabianTerhorst I tried it too before with ItemAdapter as well but it didn't work. I'll try again later. I know I've done this before and it worked, and I think I needed fastitemadapter so I could bind listeners.

**Comment by FabianTerhorst** [comment]
We are already thinking about removing FastItemAdapter because its not needed anymore and not worth the minimal reduced code.

**Comment by AllanWang** [comment]
```java
ItemAdapter<ColorPickerIItem> headerAdapter = new ItemAdapter<>();
headerAdapter.add(new ColorPickerIItem());
ItemAdapter<IconIItem> tailAdapter = new ItemAdapter<>();
tailAdapter.add(new IconIItem(GoogleMaterial.Icon.gmd_add, 0x08000000));

FastAdapter<IItem> main = FastAdapter.with(Arrays.asList(
        headerAdapter,
        adapter,
        tailAdapter
));
```

All adapters are `ItemAdapter`s, and setting the adapter to `main` didn't work

**Comment by AllanWang** [comment]
False alarm there. The issue is that I was adding items before binding to a `FastAdapter`, leading `mFastAdapter` to be null.

Maybe it's just me, but I wasn't aware of the constraints for these methods.

I think it's definitely worthwhile to document the precondition of `getFastAdapter()`.

As for helping debugging, it's up to you if you feel throwing a more specific instruction is good when getting the item from cached ids returns null, or if you feel that's too much of an overhead.

**Comment by AllanWang** [comment]
I'm going to close this since the issue was resolved.
