### ISSUE TITLE
FastAdapterDiffUtil IndexOutOfBoundsException

### ISSUE THREAD

**Issue by DummyCo** [mikepenz/FastAdapter#593]
## About this issue

Hi there! Thank you for such a great library.
I'm using FastAdapterDiffUtil widely.
In some particular cases like having two items, then modifying the second one and removing the first one I'm getting next exception:

```
java.lang.IndexOutOfBoundsException: Index: 4, Size: 3
at java.util.ArrayList.get(ArrayList.java:437)
at com.mikepenz.fastadapter.commons.utils.FastAdapterDiffUtil$FastAdapterCallback.getChangePayload(FastAdapterDiffUtil.java:158)
at android.support.v7.util.DiffUtil$DiffResult.dispatchUpdatesTo(DiffUtil.java:723)
at com.mikepenz.fastadapter.commons.utils.FastAdapterDiffUtil.set(FastAdapterDiffUtil.java:54)
at com.mikepenz.fastadapter.commons.utils.FastAdapterDiffUtil.set(FastAdapterDiffUtil.java:72)
at com.mikepenz.fastadapter.commons.utils.FastAdapterDiffUtil.set(FastAdapterDiffUtil.java:76)
at com.mikepenz.fastadapter.commons.utils.FastAdapterDiffUtil.set(FastAdapterDiffUtil.java:84)
```

Looks like _oldItems_ List is already smaller but _getChangePayload_ is still trying to access invalid position. Maybe it's possible to add bound checks, trim index to size or something else?
Thank you!

## Details
- [3.0.5] Used library version
- [27.0.2] Used support library version
- [3.1.0-alpha06] Used gradle build tools version
- [3.1 Canary 6] Used tooling / Android Studio version

**Comment by mikepenz** [comment]
@DummyCo this is known. and already reported here: https://github.com/mikepenz/FastAdapter/issues/589

There will be an update to fix this as v3.1.0 in the upcoming days
