### ISSUE TITLE
IndexOutOfBoundsException when removing items with FastAdapterDiffUtil

### ISSUE THREAD

**Issue by eygraber** [mikepenz/FastAdapter#642]
## About this issue

- Briefly describe the issue - crash when removing items

I removed all the items in a list (using the library's diff util) and I got the following crash:

```
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
                                                                       at java.util.ArrayList.get(ArrayList.java:437)
                                                                       at com.mikepenz.fastadapter.utils.DefaultItemListImpl.get(DefaultItemListImpl.java:29)
                                                                       at com.mikepenz.fastadapter.utils.DefaultItemListImpl.get(DefaultItemListImpl.java:15)
                                                                       at com.mikepenz.fastadapter.adapters.ModelAdapter.getAdapterItem(ModelAdapter.java:266)
                                                                       at com.mikepenz.fastadapter.FastAdapter.getItem(FastAdapter.java:856)
                                                                       at com.mikepenz.fastadapter.FastAdapter.getItemViewType(FastAdapter.java:930)
                                                                       at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:5451)
                                                                       at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5629)
                                                                       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5589)
                                                                       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5585)
                                                                       at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2231)
                                                                       at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1558)
                                                                       at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1518)
                                                                       at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:610)
                                                                       at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3719)
                                                                       at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3436)
                                                                       at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3988)
```

## Details
- [ ] Used library version - 3.2.4
- [ ] Used support library version - 27.0.2

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/FastAdapter/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/FastAdapter/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/FastAdapter/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/FastAdapter/releases)
- [x] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/FastAdapter/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
@eygraber how did you remove them? 

The DiffUtil does not allow that the original list is modified. You need an updated list of items which is modified

**Comment by eygraber** [comment]
@mikepenz it is not the original list. I get new data from my data source, and map those to new items. I run the diff util against that list and the adapter.

**Comment by mikepenz** [comment]
@eygraber were you able to figure something out?

**Comment by eygraber** [comment]
This was for a hackathon, so I've stopped using the app, and I don't remember if I did anything to fix it. I don't believe I did though.

**Comment by mikepenz** [comment]
@eygraber I am sorry that I was not able to react faster, currently super flooded with work... 
I'll keep an eye on other reports, as I have never seen this in the sample. If you have demo code to make it crash in the sample that would be great. 

Otherwise I think we can close this for the time being
