### ISSUE TITLE
Problem HeaderAdapter And ItemAdapter

### ISSUE THREAD

**Issue by mahdighaemi123** [mikepenz/FastAdapter#644]
Hi
Problem in ViewHolder When i set like below

```java
    private FastAdapter<ItemProducts> mFastAdapter;
    private ItemAdapter<HeaderItemShopkeeperAccount> mHeaderAdapter;
    private ItemAdapter<ItemProducts> mItemAdapter;


        mHeaderAdapter = new ItemAdapter<>();
        mItemAdapter = new ItemAdapter<>();


       mFastAdapter = FastAdapter.with(Arrays.asList(mHeaderAdapter, mItemAdapter));

        ReMyProducts.setAdapter(mFastAdapter);


       mHeaderAdapter.add(new HeaderItemShopkeeperAccount()......)
       mItemAdapter.add(new ItemProducts().withId(Product.getString("_id"))......)
```

and Logcat

```
Exception caught 
                                                         java.lang.ClassCastException: io.nevao.SmartCity.Items.HeaderItemShopkeeperAccount$ViewHolder cannot be cast to io.nevao.SmartCity.Items.ItemProducts$ViewHolder
                                                             at io.nevao.SmartCity.Items.ItemProducts.bindView(ItemProducts.java:33)
                                                             at com.mikepenz.fastadapter.listeners.OnBindViewHolderListenerImpl.onBindViewHolder(OnBindViewHolderListenerImpl.java:27)
                                                             at com.mikepenz.fastadapter.FastAdapter.onBindViewHolder(FastAdapter.java:740)
                                                             at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6541)
                                                             at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5484)
                                                             at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5750)
                                                             at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5589)
                                                             at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5585)
                                                             at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2231)
                                                             at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1558)
                                                             at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1518)
                                                             at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:610)
                                                             at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3719)
                                                             at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3436)
                                                             at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3988)
                                                             at android.view.View.layout(View.java:19586)
                                                             at android.view.ViewGroup.layout(ViewGroup.java:6053)
                                                             at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
                                                             at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
                                                             at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
                                                             at android.view.View.layout(View.java:19586)
                                                             at android.view.ViewGroup.layout(ViewGroup.java:6053)
                                                             at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
                                                             at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
                                                             at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
                                                             at android.view.View.layout(View.java:19586)
                                                             at android.view.ViewGroup.layout(ViewGroup.java:6053)
                                                             at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:611)
                                                             at android.view.View.layout(View.java:19586)
                                                             at android.view.ViewGroup.layout(ViewGroup.java:6053)
                                                             at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                             at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                             at android.view.View.layout(View.java:19586)
                                                             at android.view.ViewGroup.layout(ViewGroup.java:6053)
                                                             at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                             at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                             at android.view.View.layout(View.java:19586)
                                                             at android.view.ViewGroup.layout(ViewGroup.java:6053)
                                                             at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1080)
                                                             at android.view.View.layout(View.java:19586)
                                                             at android.view.ViewGroup.layout(ViewGroup.java:6053)
                                                             at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                             at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                             at android.view.View.layout(View.java:19586)
                                                             at android.view.ViewGroup.layout(ViewGroup.java:6053)
                                                             at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
                                                             at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
                                                             at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
                                                             at android.view.View.layout(View.java:19586)
                                                             at android.view.ViewGroup.layout(ViewGroup.java:6053)
                                                             at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                             at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                             at android.view.View.layout(View.java:19586)
                                                             at android.view.ViewGroup.layout(ViewGroup.java:6053)
                                                             at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
                                                             at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
02-19 23:30:54.065 3973-3973/io.nevao.SmartCity E/Pushe:     at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
                                                             at android.view.View.layout(View.java:19586)
                                                             at android.view.ViewGroup.layout(ViewGroup.java:6053)
                                                             at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                             at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                             at com.android.internal.policy.DecorView.onLayout(DecorView.java:758)
                                                             at android.view.View.layout(View.java:19586)
                                                             at android.view.ViewGroup.layout(ViewGroup.java:6053)
                                                             at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2484)
                                                             at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2200)
                                                             at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1386)
                                                             at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6733)
                                                             at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
                                                             at android.view.Choreographer.doCallbacks(Choreographer.java:723)
                                                             at android.view.Choreographer.doFrame(Choreographer.java:658)
                                                             at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
                                                             at android.os.Handler.handleCallback(Handler.java:789)
                                                             at android.os.Handler.dispatchMessage(Handler.java:98)
                                                             at android.os.Looper.loop(Looper.java:164)
                                                             at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                             at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
02-19 23:31:03.132 3973-4021/io.nevao.SmartCity E/Sentry: Error sending event
                                                          java.net.SocketTimeoutException: timeout
                                                              at com.android.okhttp.okio.Okio$3.newTimeoutException(Okio.java:212)
                                                              at com.android.okhttp.okio.AsyncTimeout.exit(AsyncTimeout.java:261)
                                                              at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:215)
                                                              at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
                                                              at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
                                                              at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
                                                              at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:186)
                                                              at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127)
                                                              at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:737)
                                                              at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:609)
                                                              at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:471)
                                                              at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)
                                                              at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:538)
                                                              at com.joshdholtz.sentry.Sentry$4.run(Sentry.java:392)
                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                              at java.lang.Thread.run(Thread.java:764)
                                                           Caused by: java.net.SocketException: Socket closed
                                                              at java.net.SocketInputStream.read(SocketInputStream.java:203)
                                                              at java.net.SocketInputStream.read(SocketInputStream.java:139)
                                                              at com.android.okhttp.okio.Okio$2.read(Okio.java:136)
                                                              at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
                                                              at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:306) 
                                                              at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:300) 
                                                              at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196) 
                                                              at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:186) 
                                                              at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127) 
                                                              at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:737) 
                                                              at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:609) 
                                                              at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:471) 
                                                              at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407) 
                                                              at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:538) 
                                                              at com.joshdholtz.sentry.Sentry$4.run(Sentry.java:392) 
                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
                                                              at java.lang.Thread.run(Thread.java:764) 
02-19 23:31:15.304 3973-4021/io.nevao.SmartCity E/Sentry: Error sending event
                                                          java.net.SocketTimeoutException: timeout
                                                              at com.android.okhttp.okio.Okio$3.newTimeoutException(Okio.java:212)
                                                              at com.android.okhttp.okio.AsyncTimeout.exit(AsyncTimeout.java:261)
                                                              at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:215)
                                                              at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
                                                              at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
                                                              at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
                                                              at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:186)
                                                              at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127)
                                                              at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:737)
                                                              at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:609)
                                                              at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:471)
                                                              at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)
                                                              at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseMessage(HttpURLConnectionImpl.java:534)
                                                              at com.android.tools.profiler.support.network.httpurl.TrackedHttpURLConnection.trackResponse(TrackedHttpURLConnection.java:86)
                                                              at com.android.tools.profiler.support.network.httpurl.TrackedHttpURLConnection.tryTrackResponse(TrackedHttpURLConnection.java:101)
                                                              at com.android.tools.profiler.support.network.httpurl.TrackedHttpURLConnection.getResponseCode(TrackedHttpURLConnection.java:308)
                                                              at com.android.tools.profiler.support.network.httpurl.HttpURLConnection$.getResponseCode(HttpURLConnection$.java:92)
                                                              at com.joshdholtz.sentry.Sentry$4.run(Sentry.java:392)
                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                              at java.lang.Thread.run(Thread.java:764)
                                                           Caused by: java.net.SocketException: Socket closed
                                                              at java.net.SocketInputStream.read(SocketInputStream.java:203)
                                                              at java.net.SocketInputStream.read(SocketInputStream.java:139)
                                                              at com.android.okhttp.okio.Okio$2.read(Okio.java:136)
                                                              at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
                                                              at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:306) 
                                                              at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:300) 
                                                              at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196) 
                                                              at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:186) 
                                                              at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127) 
                                                              at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:737) 
                                                              at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:609) 
                                                              at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:471) 
                                                              at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407) 
                                                              at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseMessage(HttpURLConnectionImpl.java:534) 
                                                              at com.android.tools.profiler.support.network.httpurl.TrackedHttpURLConnection.trackResponse(TrackedHttpURLConnection.java:86) 
                                                              at com.android.tools.profiler.support.network.httpurl.TrackedHttpURLConnection.tryTrackResponse(TrackedHttpURLConnection.java:101) 
                                                              at com.android.tools.profiler.support.network.httpurl.TrackedHttpURLConnection.getResponseCode(TrackedHttpURLConnection.java:308) 
                                                              at com.android.tools.profiler.support.network.httpurl.HttpURLConnection$.getResponseCode(HttpURLConnection$.java:92) 
                                                              at com.joshdholtz.sentry.Sentry$4.run(Sentry.java:392) 
                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
                                                              at java.lang.Thread.run(Thread.java:764) 
```

my ViewHolder 

Prodcuts ViewHolder
```java
protected static class ViewHolder extends RecyclerView.ViewHolder {

        //Product
        protected TextView TvTitle;
        protected TextView TvLittleDescription;
        protected TextView TvAddTime;
        protected TextView TvPrice;
        protected LinearLayout LiDiscount;
        protected TextView TvDiscountPercent;
        protected ImageView ImProductImage;
        protected LinearLayout LiBackground;
        protected ImageView ImHide;

        public ViewHolder(View view) {
            super(view);

            //Product
            TvTitle = (TextView) view.findViewById(R.id.TvTitle);
            TvLittleDescription = (TextView) view.findViewById(R.id.TvLittleDescription);
            TvAddTime = (TextView) view.findViewById(R.id.TvAddTime);
            TvPrice = (TextView) view.findViewById(R.id.TvPrice);
            LiDiscount = (LinearLayout) view.findViewById(R.id.LiDiscount);
            TvDiscountPercent = (TextView) view.findViewById(R.id.TvDiscountPercent);
            ImProductImage = (ImageView) view.findViewById(R.id.ImProductImage);
            LiBackground = (LinearLayout) view.findViewById(R.id.LiBackground);
            ImHide = (ImageView) view.findViewById(R.id.ImHide);

        }
    }
```

HeaderItemShopkeeperAccount

```java
 protected static class ViewHolder extends RecyclerView.ViewHolder {

        //ShopkeeperAccount
        protected TextView TvProductCount, TvFollowersCount, TvViewCount, TvMessageCount, TvSetting, TvOpenStore;

        public ViewHolder(View view) {
            super(view);

            //ShopkeeperAccount
            TvProductCount = (TextView) view.findViewById(R.id.TvProductCount);
            TvFollowersCount = (TextView) view.findViewById(R.id.TvFollowersCount);
            TvViewCount = (TextView) view.findViewById(R.id.TvViewCount);
            TvMessageCount = (TextView) view.findViewById(R.id.TvMessageCount);
            TvSetting = (TextView) view.findViewById(R.id.TvSetting);
            TvOpenStore = (TextView) view.findViewById(R.id.TvOpenStore);
        }
    }
```

Thanks for This lib ;)

**Comment by FabianTerhorst** [comment]
Does HeaderItemShopkeeperAccount inherit from ItemProducts?

**Comment by mikepenz** [comment]
@mahdighaemi123 what are the identifiers for those 2 item types?

**Comment by mikepenz** [comment]
https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/MultiselectSampleActivity.java#L62

**Comment by mikepenz** [comment]
Please report back. Close until any new details are provided
