### ISSUE TITLE
Unable to merge dex error

### ISSUE THREAD

**Issue by huseyinzorlu** [mikepenz/FastAdapter#650]
Hi 

i am trying almost 3 hours to fix problem but didnot find any solution. Is somebody face this problem ?
I double check my dependencies to not add too many method. Today I tried to use fast adapter after that i face over method exception. I tried to use multi dex option but cannot fix. 

`Caused by: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex
	at com.android.builder.dexing.DexArchiveMergerCallable.call(DexArchiveMergerCallable.java:72)
	at com.android.builder.dexing.DexArchiveMergerCallable.call(DexArchiveMergerCallable.java:36)
	... 121 more
Caused by: com.android.dex.DexException: Multiple dex files define Lcom/mikepenz/fastadapter/ISubItem;
	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:661)
	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:616)
	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:598)
	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
	at com.android.dx.merge.DexMerger.merge(DexMerger.java:198)
	at com.android.builder.dexing.DexArchiveMergerCallable.call(DexArchiveMergerCallable.java:61)
	... 122 more`

**Comment by huseyinzorlu** [comment]
I dont how but now i am fixed.

Normally i  was add : 
    implementation 'com.mikepenz:fastadapter:3.2.4@aar'
    implementation 'com.mikepenz:fastadapter-commons:3.2.4@aar'
    implementation 'com.mikepenz:materialize:1.1.2@aar'

But when i change to:
    implementation 'com.mikepenz:fastadapter:3.2.4@aar'
    implementation 'com.mikepenz:fastadapter-extensions-expandable:3.2.4@aar'
    implementation 'com.mikepenz:fastadapter-commons:3.2.4@aar'
    implementation 'com.mikepenz:materialize:1.1.2@aar'

Error is gone. 

Upps maybe should be check somewhere.

Thanks for your FastAdapter. it powerfull 👍
