### ISSUE TITLE
IndexOutOfBoundsException when using drag and drop

### ISSUE THREAD

**Issue by strangerweather** [mikepenz/FastAdapter#651]
## About this issue

- I am getting the following error: java.lang.IndexOutOfBoundsException: Index: 13, Size: 0
- How can the issue be reproduced / sample code: I am using SimpleItem and SimpleItemListActivity without any changes from your Github files (for testing purposes). 

## Details
- [ ] Used library version: 3.2.4
- [ ] Used support library version: 3.2.4
- [ ] Used gradle build tools version: 3.0.1
- [ ] Used tooling / Android Studio version: 3.0.1
- [ ] Other used libraries, potential conflicting libraries: None

## Checklist

- [ ] Searched for [similar issues](https://github.com/mikepenz/FastAdapter/issues)
- [ ] Checked out the [sample application](https://github.com/mikepenz/FastAdapter/tree/develop/app)
- [ ] Read the [README](https://github.com/mikepenz/FastAdapter/blob/develop/README.md)
- [ ] Checked out the [CHANGELOG](https://github.com/mikepenz/FastAdapter/releases)
- [ ] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/FastAdapter/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
@strangerweather can you please provide more details on how this crash occurs in this sample? I tested it with the current released version on my Pixel 2 XL and I can not reproduce the crash

**Comment by strangerweather** [comment]
Hi, basically I can long click, lift and move the item. However, other items don't move to make space for it and the crash occurs at that point, when I hover the item over another item, before dropping it.

**Comment by FabianTerhorst** [comment]
Im also not able to reproduce the crash, can you post the full crash log or an video?

**Comment by strangerweather** [comment]
Sure, here is the log:

`FATAL EXCEPTION: main
                                                                            Process: com.strangerweather.nat.test, PID: 2720
                                                                            java.lang.IndexOutOfBoundsException: Index: 2, Size: 0
                                                                                at java.util.ArrayList.get(ArrayList.java:411)
                                                                                at com.mikepenz.fastadapter.utils.DefaultItemListImpl.move(DefaultItemListImpl.java:68)
                                                                                at com.mikepenz.fastadapter.adapters.ModelAdapter.move(ModelAdapter.java:471)
                                                                                at com.mikepenz.fastadapter_extensions.utilities.DragDropUtil.onMove(DragDropUtil.java:55)
                                                                                at com.strangerweather.nat.test.SimpleItemListActivity.itemTouchOnMove(SimpleItemListActivity.java:201)
                                                                                at com.mikepenz.fastadapter_extensions.drag.SimpleDragCallback.onMove(SimpleDragCallback.java:95)
                                                                                at android.support.v7.widget.helper.ItemTouchHelper.moveIfNecessary(ItemTouchHelper.java:858)
                                                                                at android.support.v7.widget.helper.ItemTouchHelper$2.onTouchEvent(ItemTouchHelper.java:373)
                                                                                at android.support.v7.widget.RecyclerView.dispatchOnItemTouch(RecyclerView.java:2836)
                                                                                at android.support.v7.widget.RecyclerView.onTouchEvent(RecyclerView.java:2979)
                                                                                at android.view.View.dispatchTouchEvent(View.java:10023)
                                                                                at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2626)
                                                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2307)
                                                                                at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
                                                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
                                                                                at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
                                                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
                                                                                at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
                                                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
                                                                                at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
                                                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
                                                                                at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
                                                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
                                                                                at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
                                                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
                                                                                at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
                                                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
                                                                                at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
                                                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
                                                                                at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:413)
                                                                                at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1808)
                                                                                at android.app.Activity.dispatchTouchEvent(Activity.java:3061)
                                                                                at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
                                                                                at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:375)
                                                                                at android.view.View.dispatchPointerEvent(View.java:10243)
                                                                                at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4438)
                                                                                at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4306)
                                                                                at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
                                                                                at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3906)
                                                                                at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3872)
                                                                                at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3999)
                                                                                at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3880)
                                                                                at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4056)
                                                                                at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
                                                                                at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3906)
                                                                                at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3872)
                                                                                at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3880)
                                                                                at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
                                                                                at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6246)
                                                                                at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6220)
03-10 11:53:05.205 2720-2720/com.strangerweather.nat.test E/AndroidRuntime:     at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6181)
                                                                                at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6349)
                                                                                at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                                                at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
                                                                                at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
                                                                                at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6320)
                                                                                at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6372)
                                                                                at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
                                                                                at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                                                at android.view.Choreographer.doFrame(Choreographer.java:615)
                                                                                at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                                                                                at android.os.Handler.handleCallback(Handler.java:751)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                at android.os.Looper.loop(Looper.java:154)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)`

Line 201 I have : `DragDropUtil.onMove(itemAdapter, oldPosition, newPosition);`

**Comment by mikepenz** [comment]
Which Android version do you use? Which phone? 

No matter what I try, it won't crash for me in the sample app

**Comment by strangerweather** [comment]
I've tried on my android emulator phones as well as on my Huawei P9 Lite and my Samsung Galaxy Tab 2.
Don't worry too much because I have moved on (I have set up drag and drop and swipe to dismiss on a regular recyclerview, using no libraries). You're welcome to close the issue. But in any case thanks for the libraries and for trying to help!

**Comment by mikepenz** [comment]
Thank you very much! 

All the best
