### ISSUE TITLE
IndexOutOfBoundsException

### ISSUE THREAD

**Issue by eakteam** [mikepenz/FastAdapter#670]
Somebody help with this : 

```
Fatal Exception: java.lang.IndexOutOfBoundsException: Invalid index 4, size is 4
       at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:251)
       at java.util.ArrayList.get(ArrayList.java:304)
       at com.mikepenz.fastadapter.FastAdapter.com.mikepenz.fastadapter.utils.DefaultTypeInstanceCache.register(SourceFile
:5)
       at com.mikepenz.fastadapter.FastAdapter.getItemViewType(SourceFile
:1)
       at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(SourceFile
:62)
       at android.support.v7.widget.RecyclerView$Recycler.recycleAndClearCachedViews(SourceFile
:1)
       at android.support.v7.widget.LinearLayoutManager$LayoutState.next(SourceFile
:9)
       at android.support.v7.widget.LinearLayoutManager.collectInitialPrefetchPositions(SourceFile
:1)
       at android.support.v7.widget.LinearLayoutManager.updateLayoutState(SourceFile
:13)
       at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(SourceFile
:126)
       at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(SourceFile
:8)
       at android.support.v7.widget.RecyclerView.dispatchLayout(SourceFile
:9)
       at android.support.v7.widget.RecyclerView.onLayout(SourceFile
:3)
       at android.view.View.layout(View.java:14061)
       at android.view.ViewGroup.layout(ViewGroup.java:4374)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1655)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1513)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1426)
       at android.view.View.layout(View.java:14061)
       at android.view.ViewGroup.layout(ViewGroup.java:4374)
       at android.support.v4.view.ViewPager.onLayout(SourceFile
:36)
       at android.view.View.layout(View.java:14061)
       at android.view.ViewGroup.layout(ViewGroup.java:4374)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:948)
       at android.view.View.layout(View.java:14061)
       at android.view.ViewGroup.layout(ViewGroup.java:4374)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1655)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1513)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1426)
       at android.view.View.layout(View.java:14061)
       at android.view.ViewGroup.layout(ViewGroup.java:4374)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:948)
       at android.view.View.layout(View.java:14061)
       at android.view.ViewGroup.layout(ViewGroup.java:4374)
       at android.support.v4.widget.DrawerLayout.onLayout(SourceFile
:10)
       at android.view.View.layout(View.java:14061)
       at android.view.ViewGroup.layout(ViewGroup.java:4374)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
       at android.view.View.layout(View.java:14061)
       at android.view.ViewGroup.layout(ViewGroup.java:4374)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1655)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1513)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1426)
       at android.view.View.layout(View.java:14061)
       at android.view.ViewGroup.layout(ViewGroup.java:4374)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
       at android.view.View.layout(View.java:14061)
       at android.view.ViewGroup.layout(ViewGroup.java:4374)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1655)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1513)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1426)
       at android.view.View.layout(View.java:14061)
       at android.view.ViewGroup.layout(ViewGroup.java:4374)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
       at android.view.View.layout(View.java:14061)
       at android.view.ViewGroup.layout(ViewGroup.java:4374)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:1986)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1807)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4464)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
       at android.view.Choreographer.doCallbacks(Choreographer.java:555)
       at android.view.Choreographer.doFrame(Choreographer.java:525)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
       at android.os.Handler.handleCallback(Handler.java:615)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4895)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:994)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:761)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by mikepenz** [comment]
Is this reproducible in the sample?

If not. Please provide a more precise error description by following the github issue template

**Comment by eakteam** [comment]
Hello , thanks for replying , but crashlytics doesn't give me what is causing this , only that detail above.
And my project is really big, i don't know what line throw this fatal exception. Anyway i will try to make some tests with hope to find it :)

**Comment by mikepenz** [comment]
Thank you very much please report back with more details ;)
