### ISSUE TITLE
IndexOutOfBoundsException: Index: 1, Size: 1

### ISSUE THREAD

**Issue by eakteam** [mikepenz/FastAdapter#694]
Don't know where it happen because the project is very large and it uses this library in every recycler view. Any tip or hint to try to reproduce it in my phone ? Because everything seems ok when i do the tests

```
Fatal Exception: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
       at java.util.ArrayList.get(ArrayList.java:437)
       at com.mikepenz.fastadapter.FastAdapter.addExtension(SourceFile
:5)
       at com.mikepenz.fastadapter.FastAdapter.getItemViewType(SourceFile
:1)
       at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(SourceFile
:62)
       at android.support.v7.widget.LinearLayoutManager$LayoutState.android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(SourceFile
:10)
       at android.support.v7.widget.LinearLayoutManager.onAnchorReady(SourceFile
:1)
       at android.support.v7.widget.LinearLayoutManager.onAnchorReady(SourceFile
:13)
       at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(SourceFile
:126)
       at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(SourceFile
:8)
       at android.support.v7.widget.RecyclerView.dispatchLayout(SourceFile
:7)
       at android.support.v7.widget.RecyclerView.onLayout(SourceFile
:3)
       at android.view.View.layout(View.java:20836)
       at android.view.ViewGroup.layout(ViewGroup.java:6401)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
       at android.view.View.layout(View.java:20836)
       at android.view.ViewGroup.layout(ViewGroup.java:6401)
       at android.support.v4.view.ViewPager.onLayout(SourceFile
:36)
       at android.view.View.layout(View.java:20836)
       at android.view.ViewGroup.layout(ViewGroup.java:6401)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1080)
       at android.view.View.layout(View.java:20836)
       at android.view.ViewGroup.layout(ViewGroup.java:6401)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
       at android.view.View.layout(View.java:20836)
       at android.view.ViewGroup.layout(ViewGroup.java:6401)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1080)
       at android.view.View.layout(View.java:20836)
       at android.view.ViewGroup.layout(ViewGroup.java:6401)
       at android.support.v4.widget.DrawerLayout.onLayout(SourceFile
:10)
       at android.view.View.layout(View.java:20836)
       at android.view.ViewGroup.layout(ViewGroup.java:6401)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:20836)
       at android.view.ViewGroup.layout(ViewGroup.java:6401)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
       at android.view.View.layout(View.java:20836)
       at android.view.ViewGroup.layout(ViewGroup.java:6401)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:20836)
       at android.view.ViewGroup.layout(ViewGroup.java:6401)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
       at android.view.View.layout(View.java:20836)
       at android.view.ViewGroup.layout(ViewGroup.java:6401)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at com.android.internal.policy.DecorView.onLayout(DecorView.java:944)
       at android.view.View.layout(View.java:20836)
       at android.view.ViewGroup.layout(ViewGroup.java:6401)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2911)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2598)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1742)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7763)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
       at android.view.Choreographer.doCallbacks(Choreographer.java:723)
       at android.view.Choreographer.doFrame(Choreographer.java:658)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6938)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

**Comment by eakteam** [comment]
I think that this is happening when i add items in recyclerview, and after some conditions, delete, add new or move they to another position.
When remove i call : `fastadapter.notifyItemRemoved(position);`
When move : 
```
fastadapter.move(finalI, finalA);
fastadapter.notifyItemMoved(finalI, finalA);
```

**Comment by mikepenz** [comment]
you don't have to notify. the adapter will handle that for you already.

also make sure calls are done on the UI thread

**Comment by eakteam** [comment]
ohh i see, but why there are those methods public ? 
Yes all the calls are maded to UI thread, but i'm going crazy with that bug , maybe it is on my side, but it report crashes to this library not in my java code

**Comment by FabianTerhorst** [comment]
When doing specific notifies for not existing items the recyclerview will ask the adapter for this items, which results in an crash here: https://github.com/mikepenz/FastAdapter/blob/develop/library-core/src/main/java/com/mikepenz/fastadapter/FastAdapter.java#L928
Surprisingly it isn't an npe because getItem should return null for not existing items, but it isn't in this specific case. It looks like there is an missing indes check there to prevent this error from happening. But not sure which type to return for items that are not existing.

**Comment by eakteam** [comment]
Understand thank you !
