### ISSUE TITLE
Expandables: Is it possible to drag child items to parents and vice versa?

### ISSUE THREAD

**Issue by Androidjent** [mikepenz/FastAdapter#726]
Hey guys,

first of all, thank you very much for an awesome library :-)

I would like to have a windows explorer-like structure of expandable listview niodes, where I can drag item not only within their respective level, but also to child and parent levels. Is this doable with Fastadapter?

For fun, I tinkered with the sample app and put the draggable touchhelper on the simple expandle sample activity. If I drag downwards, the child item is simply skipped and I merely move the item on the respective node level. If I drag an item upwards, into the parent node, the app crashes (log is at the end). 

I doubt that this is within the normal use of Fastadapter. Is it not possible or am I making a simple mistake? Below is my Activity and the crash log.

Activity (modification of sample app):
`public class ExpandableSampleActivity extends AppCompatActivity implements ItemTouchCallback {
    //save our FastAdapter
    private FastItemAdapter<SimpleSubExpandableItem> fastItemAdapter;
    private ExpandableExtension<SimpleSubExpandableItem> expandableExtension;

    //drag & drop
    private SimpleDragCallback touchCallback;
    private ItemTouchHelper touchHelper;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        findViewById(android.R.id.content).setSystemUiVisibility(findViewById(android.R.id.content).getSystemUiVisibility() | View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR);
        //as we use an icon from Android-Iconics via xml we add the IconicsLayoutInflater
        //https://github.com/mikepenz/Android-Iconics
        LayoutInflaterCompat.setFactory(getLayoutInflater(), new IconicsLayoutInflater(getDelegate()));
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_sample);

        // Handle Toolbar
        Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);
        getSupportActionBar().setTitle(R.string.sample_collapsible);

        //style our ui
        new MaterializeBuilder().withActivity(this).build();

        //create our FastAdapter
        fastItemAdapter = new FastItemAdapter<>();
        fastItemAdapter.withSelectable(true);
        expandableExtension = new ExpandableExtension<>();
        //expandableExtension.withOnlyOneExpandedItem(true);
        fastItemAdapter.addExtension(expandableExtension);

        fastItemAdapter.withEventHook(new SimpleSubExpandableItem.YourMomIsExpandableEvent());

        //get our recyclerView and do basic setup
        RecyclerView rv = (RecyclerView) findViewById(R.id.rv);
        rv.setLayoutManager(new LinearLayoutManager(this));
        rv.setItemAnimator(new SlideDownAlphaAnimator());
        rv.setAdapter(fastItemAdapter);

        //fill with some sample data
        List<SimpleSubExpandableItem> items = new ArrayList<>();
        AtomicInteger identifier = new AtomicInteger(1);
        for (int i = 1; i <= 10; i++) {
            SimpleSubExpandableItem parent = new SimpleSubExpandableItem();
            parent.withName("Test " + i).withIdentifier(identifier.getAndIncrement());

            List<IItem> subItems = new LinkedList<>();
            for (int ii = 1; ii <= 5; ii++) {
                SimpleSubExpandableItem subItem = new SimpleSubExpandableItem();
                subItem.withName("-- SubTest " + ii).withIdentifier(identifier.getAndIncrement());

                List<IItem> subSubItems = new LinkedList<>();
                for (int iii = 1; iii <= 3; iii++) {
                    SimpleSubExpandableItem subSubItem = new SimpleSubExpandableItem();
                    subSubItem.withName("---- SubSubTest " + iii).withIdentifier(identifier.getAndIncrement());

                    List<IItem> subSubSubItems = new LinkedList<>();
                    for (int iiii = 1; iiii <= 4; iiii++) {
                        SimpleSubExpandableItem subSubSubItem = new SimpleSubExpandableItem();
                        subSubSubItem.withName("----- SubSubSubTest " + iiii).withIdentifier(identifier.getAndIncrement());

                        List<IItem> ItemListThatWontShow = new LinkedList<>();
                        for (int iiiii = 1; iiiii <= 4; iiiii++) {
                            SimpleSubExpandableItem ItemThatWontShow = new SimpleSubExpandableItem();
                            ItemThatWontShow.withName("------ This Part is wont open " + iiiii).withIdentifier(identifier.getAndIncrement());
                            ItemListThatWontShow.add(ItemThatWontShow);
                        }
                        subSubSubItem.withSubItems(ItemListThatWontShow);
                        subSubSubItems.add(subSubSubItem);
                    }
                    subSubItem.withSubItems(subSubSubItems);
                    subSubItems.add(subSubItem);
                }
                subItem.withSubItems(subSubItems);
                subItems.add(subItem);
            }
            parent.withSubItems(subItems);
            items.add(parent);
        }
        fastItemAdapter.add(items);

        //restore selections (this has to be done after the items were added
        fastItemAdapter.withSavedInstanceState(savedInstanceState);
/*
        //configure our fastAdapter
        fastItemAdapter.withOnClickListener(new OnClickListener<IItem>() {
            @Override
            public boolean onClick(@Nullable View v, IAdapter<IItem> adapter, IItem item, int position) {
                Toast.makeText(v.getContext(), "pos = "+position, Toast.LENGTH_LONG).show();
                return false;
            }
        });*/

        //add drag and drop for item
        touchCallback = new SimpleDragCallback(this);
        touchHelper = new ItemTouchHelper(touchCallback); // Create ItemTouchHelper and pass with parameter the SimpleDragCallback
        touchHelper.attachToRecyclerView(rv); // Attach ItemTouchHelper to RecyclerView

        //set the back arrow in the toolbar
        getSupportActionBar().setDisplayHomeAsUpEnabled(true);
        getSupportActionBar().setHomeButtonEnabled(false);
    }

    @Override
    protected void onSaveInstanceState(Bundle outState) {
        //add the values which need to be saved from the adapter to the bundle
        outState = fastItemAdapter.saveInstanceState(outState);
        super.onSaveInstanceState(outState);
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        //handle the click on the back arrow click
        switch (item.getItemId()) {
            case android.R.id.home:
                onBackPressed();
                return true;

            default:
                return super.onOptionsItemSelected(item);
        }
    }

    @Override
    public boolean itemTouchOnMove(int oldPosition, int newPosition) {
        Toast.makeText(getApplicationContext(), "pos = "+oldPosition+" posnew ="+newPosition, Toast.LENGTH_LONG).show();
        DragDropUtil.onMove(fastItemAdapter.getItemAdapter(), oldPosition, newPosition);  // change
        return true;
    }

    @Override
    public void itemTouchDropped(int oldPosition, int newPosition) {

    }
}`

Crash log:
`10-03 22:57:59.649 21349-21349/com.mikepenz.fastadapter.app E/InputEventReceiver: Exception dispatching input event.
10-03 22:57:59.651 21349-21349/com.mikepenz.fastadapter.app D/AndroidRuntime: Shutting down VM
10-03 22:57:59.659 21349-21349/com.mikepenz.fastadapter.app E/AndroidRuntime: FATAL EXCEPTION: main
                                                                              Process: com.mikepenz.fastadapter.app, PID: 21349
                                                                              java.lang.IndexOutOfBoundsException: Index: -1, Size: 14
                                                                                  at java.util.ArrayList.add(ArrayList.java:457)
                                                                                  at com.mikepenz.fastadapter.utils.DefaultItemListImpl.move(DefaultItemListImpl.java:74)
                                                                                  at com.mikepenz.fastadapter.adapters.ModelAdapter.move(ModelAdapter.java:476)
                                                                                  at com.mikepenz.fastadapter_extensions.utilities.DragDropUtil.onMove(DragDropUtil.java:51)
                                                                                  at com.mikepenz.fastadapter.app.ExpandableSampleActivity.itemTouchOnMove(ExpandableSampleActivity.java:168)
                                                                                  at com.mikepenz.fastadapter_extensions.drag.SimpleDragCallback.onMove(SimpleDragCallback.java:95)
                                                                                  at androidx.recyclerview.widget.ItemTouchHelper.moveIfNecessary(ItemTouchHelper.java:881)
                                                                                  at androidx.recyclerview.widget.ItemTouchHelper$2.onTouchEvent(ItemTouchHelper.java:387)
                                                                                  at androidx.recyclerview.widget.RecyclerView.dispatchOnItemTouch(RecyclerView.java:2947)
                                                                                  at androidx.recyclerview.widget.RecyclerView.onTouchEvent(RecyclerView.java:3090)
                                                                                  at android.view.View.dispatchTouchEvent(View.java:10024)
                                                                                  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2626)
                                                                                  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2307)
                                                                                  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
                                                                                  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
                                                                                  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
                                                                                  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
                                                                                  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
                                                                                  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
                                                                                  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
                                                                                  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
                                                                                  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
                                                                                  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
                                                                                  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
                                                                                  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
                                                                                  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
                                                                                  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
                                                                                  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
                                                                                  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
                                                                                  at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:416)
                                                                                  at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1808)
                                                                                  at android.app.Activity.dispatchTouchEvent(Activity.java:3065)
                                                                                  at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
                                                                                  at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
                                                                                  at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:378)
                                                                                  at android.view.View.dispatchPointerEvent(View.java:10244)
                                                                                  at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4444)
                                                                                  at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4312)
                                                                                  at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3859)
                                                                                  at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3912)
                                                                                  at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3878)
                                                                                  at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4005)
                                                                                  at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3886)
                                                                                  at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4062)
                                                                                  at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3859)
                                                                                  at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3912)
                                                                                  at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3878)
                                                                                  at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3886)
                                                                                  at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3859)
10-03 22:57:59.659 21349-21349/com.mikepenz.fastadapter.app E/AndroidRuntime:     at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6253)
                                                                                  at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6227)
                                                                                  at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6188)
                                                                                  at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6356)
                                                                                  at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                                                  at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
                                                                                  at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
                                                                                  at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6327)
                                                                                  at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6379)
                                                                                  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
                                                                                  at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                                                  at android.view.Choreographer.doFrame(Choreographer.java:615)
                                                                                  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                                                                                  at android.os.Handler.handleCallback(Handler.java:751)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                  at android.os.Looper.loop(Looper.java:154)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:6186)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)`

**Comment by Androidjent** [comment]
Hi Mike,

sorry for responding so late, I was busy. I tinkered with the old issue again after reading your reply. If I get right, you mean something like this (in pseudo code):

```
@Override
    public boolean itemTouchOnMove(int oldPosition, int newPosition) {
        fastItemAdapter.getListofOldPosition(oldPosition).move;
fastItemAdapter.getListofCurrentPosition(newPosition).Insert;
        return true;
    }
```

Can you please tell me what methods to use? I am outside of my expertise and hope I am not embarrassing myself on Java basics, but I don't get how to access current lists or certain child lists.

Thanks for all your work!

**Comment by Androidjent** [comment]
Hi Mike,

I think I will try if I can make it with an extension of List<SimpleSubExpandableItem> that handles about five sublevels via position. This class could be inserted in the itemadapter, like the usual list of items.

U think this could work?
