### ISSUE TITLE
ConcurrentModificationException when using setNewList

### ISSUE THREAD

**Issue by bjarn** [mikepenz/FastAdapter#774]
## About this issue

- When calling the setNewList function on an adapter, it might throw a ConcurrentModificationException.
- I haven't been able to reproduce it myself, but a few hundred of my users (there are >100K of them), experience this issue occasionally.

Here's the stacktrace:
```
Fatal Exception: java.util.ConcurrentModificationException
       at java.util.ArrayList$Itr.next(ArrayList.java:860)
       at com.mikepenz.fastadapter.adapters.ModelAdapter.intercept(ModelAdapter.java:111)
       at com.mikepenz.fastadapter.adapters.ModelAdapter.setNewList(ModelAdapter.java:253)
       at com.mikepenz.fastadapter.adapters.ModelAdapter.setNewList(ModelAdapter.java:242)
       at xx.xx.xx.xx.ui.search.SearchFragment.addSearchResultsToList(SearchFragment.java:128)
       at xx.xx.xx.xx.ui.search.SearchFragment._$_findCachedViewById(SearchFragment.java:1)
       at xx.xx.xx.xx.ui.search.SearchFragment.access$addSearchResultsToList(SearchFragment.java:46)
       at xx.xx.xx.xx.ui.search.SearchFragment$onCreate$1.invoke(SearchFragment.java:58)
       at xx.xx.xx.xx.ui.search.SearchFragment$onCreate$1.invoke(SearchFragment.java:46)
       at net.realify.core.utils.ViewModelHelpersKt$sam$androidx_lifecycle_Observer$0.onChanged(ViewModelHelpersKt.java:2)
       at androidx.lifecycle.LiveData.considerNotify(LiveData.java:113)
       at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:131)
       at androidx.lifecycle.LiveData.setValue(LiveData.java:289)
       at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:33)
       at androidx.lifecycle.LiveData$1.run(LiveData.java:91)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:7000)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
```

The following function is being called by a LiveData observer:
```kotlin
   private fun addSearchResultsToList(items: List<IItem<*>>) {
        adapter.setNewList(items)
    }
```

## Details
- [4.0.0-rc04] Used library version
- [AndroidX AppCompat 1.0.2] Used support library version
- [28.0.3] Used gradle build tools version
- [3.4.1] Used tooling / Android Studio version

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/FastAdapter/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/FastAdapter/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/FastAdapter/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/FastAdapter/releases)
- [x] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/FastAdapter/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
You could make a copy of your list before passing it into `setNewList` as `setNewList` needs to iterate over the lists contents, and if you modify it in your application you can cause this exception.

**Comment by mikepenz** [comment]
Have you had a chance to check this problem again?

**Comment by bjarn** [comment]
Haven't released an update for my app yet, but the fix has been applied and I wasn't able to reproduce it anymore.

I'll keep you updated!

**Comment by mikepenz** [comment]
Thank you very much. Will close for the time being. Please report back or re-open if it still causes problems
