### ISSUE TITLE
Crash with PagedModelAdapter

### ISSUE THREAD

**Issue by RobbWatershed** [mikepenz/FastAdapter#843]
## About this issue

I'm using `PagedModelAdapter` to handle the display of a book library. I'm fetching data using `LivePagedListBuilder` with placeholders enabled.

When working on large libraries (100+ books), I noticed that, when changing the ordering of the list (e.g. A->Z to Z->A, which implies everything on screen gets instantly recycled to display the other end of the list) :
 - `PagedItemListImpl` crashes very often after calling `PagedModelAdapter.submitList` (see stacktrace below)
 - While debugging, the position where the crash happens has no obvious issue (i.e. not out of bounds by any means)
 - The crash is completely avoided when disabling placeholders in `LivePagedListBuilder`

=> Could it be that `PagedItemListImpl.get` stumbles upon one of the `null` values generated as placeholders and overreacts by firing a `RuntimeException` ?

```
2019-12-07 19:59:46.379 28724-28724/me.app.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: me.app.debug, PID: 28724
    java.lang.RuntimeException: No item found at position
        at com.mikepenz.fastadapter.paged.PagedItemListImpl.get(PagedItemListImpl.kt:40)
        at com.mikepenz.fastadapter.paged.PagedModelAdapter.getAdapterItem(PagedModelAdapter.kt:144)
        at com.mikepenz.fastadapter.FastAdapter.getItem(FastAdapter.kt:505)
        at com.mikepenz.fastadapter.FastAdapter.getItemViewType(FastAdapter.kt:581)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6186)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
        at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:3540)
        at android.view.View.measure(View.java:23454)
        at androidx.constraintlayout.widget.ConstraintLayout.internalMeasureChildren(ConstraintLayout.java:1227)
        at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(ConstraintLayout.java:1572)
        at android.view.View.measure(View.java:23454)
        at androidx.drawerlayout.widget.DrawerLayout.onMeasure(DrawerLayout.java:1119)
        at android.view.View.measure(View.java:23454)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6834)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
        at android.view.View.measure(View.java:23454)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6834)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1565)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:847)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:726)
        at android.view.View.measure(View.java:23454)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6834)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:23454)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6834)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1565)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:847)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:726)
        at android.view.View.measure(View.java:23454)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6834)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:847)
        at android.view.View.measure(View.java:23454)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2954)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1753)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2041)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1636)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7946)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1092)
        at android.view.Choreographer.doCallbacks(Choreographer.java:893)
        at android.view.Choreographer.doFrame(Choreographer.java:812)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1078)
        at android.os.Handler.handleCallback(Handler.java:907)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
2019-12-07 19:59:46.381 28724-28724/me.app.debug E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
2019-12-07 19:59:47.034 28724-29031/me.app.debug D/FA: Logging event (FE): app_exception(_ae), Bundle[{ga_event_origin(_o)=clx, _r=1, ga_screen_class(_sc)=LibraryActivity, ga_screen_id(_si)=-2421316634838089164, timestamp=1575745186417, fatal=1}]
2019-12-07 19:59:47.149 28724-28724/me.app.debug I/Process: Sending signal. PID: 28724 SIG: 9
```

## Details
- [x] Used library version : 4.1.1
- [x] Used support library version : 1.1.0
- [x] Used gradle build tools version : v3.5.2
- [x] Used tooling / Android Studio version : v3.5.3
- [x] Other used libraries, potential conflicting libraries : Not that I know of

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/FastAdapter/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/FastAdapter/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/FastAdapter/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/FastAdapter/releases)
- [x] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/FastAdapter/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
Thank you so much for reporting this problem. I have looked into the problem, and your conclusion is right. 

The current implementation of PagedItemLists did not yet fully support placeholders, as the adapter will not understand what to display in such a situation. 

I have now provided an interceptor to allow creating the placeholder in case a `null` is returned. 

Please let me know what you think about this API and if it is sufficient for your usecase

https://github.com/mikepenz/FastAdapter/pull/847

**Comment by RobbWatershed** [comment]
Thanks a bunch for investigating and fixing that issue ! ❤️ 

I've reviewed the change you made to the `PagedModelAdapter` API.

From what I see, I understand the public constructor has changed but a default value has been provided for the new `placeholderInterceptor` argument, probably to avoid breaking every single implementation upon library update.

The consequence is people who haven't been paying attention to the changelog will get the ```No item found at position``` `RuntimeException` implemented in `PagedItemListImpl.getDefaultPlaceholderInterceptor` and might get a little confused.

If everything I said so far makes sense, I'd suggest making the exception message much more explicit, and provide guidance with it, e.g. ```No item found at position <position> and no default placeholder defined. You should define a default placeholder while initializing PagedModelAdapter```

**Comment by mikepenz** [comment]
@RobbWatershed yes exactly. the additional function you can pass in, allows you to provide the relevant placeholder element you want to display. And the default value got defined to not break existing usages, and have the same default behavior. 

You are absolutely right that we should provide a more precise error message in a case somebody uses placeholders but doesn't look at the API very specifically. 

In addition I would love to add placeholders to the sample app to also have a more precise way to showcase this behavior and also have an indirect testcase via the sample. 

If you get a chance, would you be so kind to extend the sample to have a similar behavior as what you expect? 

Thanks again for reporting the issue and providing such precise information

**Comment by RobbWatershed** [comment]
Sure. I'll see what I can do.

Any ETA for the publishing of the fix ?

**Comment by mikepenz** [comment]
I am gonna release v4.1.2-rc01 in the next few minutes. and v4.1.2 after ensuring that everything seems stable. e.g. also hopefully gathering some feedback from you :)

**Comment by RobbWatershed** [comment]
Awesome, thanks a lot man !  I'll give you some feedback in the next days.

Btw I have forked and built the sample app successfuly. However, since I'm new to Kotlin, adapting it properly might take a little while.

**Comment by mikepenz** [comment]
Thank you so much. that is really helpful. 

If you got some questions regarding Kotlin let me know. But I highly suggest that you give it a spin :) Kotlin is awesome.

**Comment by RobbWatershed** [comment]
Alright, I just tested my app with v4.1.2-rc01 and now it works like a charm. As far as I'm concerned, we're good to go !

**Comment by mikepenz** [comment]
sounds great. thank you so much. if you have suggestions about improvements to this let me know :)
