### ISSUE TITLE
Exception with PagedModelAdapter.clear() on Fragment.onDestroyView()

### ISSUE THREAD

**Issue by Rasalexman** [mikepenz/FastAdapter#858]
- Crash after calling fragment lifecycle method onDestroyView
- create PagedModelAdapter(...) and call `PagedModelAdapter.clear` after `super.onDestroyView()`

- [ 5.0.0-a01] Used library version
- [ androidx.appcompat:appcompat:1.1.0] Used support library version
- [ 3.5.2] Used gradle build tools version
- [3.4.2 ] Used tooling / Android Studio version

```
override fun onDestroyView() {
        super.onDestroyView()
        itemAdapter.clear()
}
```

## Checklist
```
java.lang.UnsupportedOperationException: Not supported
        at com.mikepenz.fastadapter.paged.PagedModelAdapter.clear(PagedModelAdapter.kt:228)
        at com.rasalexman.core.presentation.BasePagedRecyclerFragment.clearAdapter(BasePagedRecyclerFragment.kt:219)
        at com.rasalexman.core.presentation.BasePagedRecyclerFragment.clearFastAdapter(BasePagedRecyclerFragment.kt:225)
        at com.rasalexman.core.presentation.BasePagedRecyclerFragment.onDestroyView(BasePagedRecyclerFragment.kt:95)
        at com.rasalexman.tabhome.presentation.movieslist.MoviesListFragment.onDestroyView(Unknown Source:0)
        at androidx.fragment.app.Fragment.performDestroyView(Fragment.java:2905)
        at androidx.fragment.app.FragmentManager.destroyFragmentView(FragmentManager.java:1386)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1295)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1398)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1476)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1541)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2858)
        at androidx.fragment.app.FragmentManager.dispatchDestroyView(FragmentManager.java:2837)
        at androidx.fragment.app.Fragment.performDestroyView(Fragment.java:2899)
        at androidx.fragment.app.FragmentManager.destroyFragmentView(FragmentManager.java:1386)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1295)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1398)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1476)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1541)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2858)
        at androidx.fragment.app.FragmentManager.dispatchDestroyView(FragmentManager.java:2837)
        at androidx.fragment.app.Fragment.performDestroyView(Fragment.java:2899)
        at androidx.fragment.app.FragmentManager.destroyFragmentView(FragmentManager.java:1386)
        at androidx.fragment.app.FragmentManager.removeCancellationSignal(FragmentManager.java:734)
        at androidx.fragment.app.FragmentManager$2.onComplete(FragmentManager.java:374)
        at androidx.fragment.app.FragmentAnim$2$1.run(FragmentAnim.java:175)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by mikepenz** [comment]
The `PagedItemListImpl` does not contain a `clear()` method, as such the `FastAdapter` does not offer this functionality in the paged case. 

This works as intended. 
The error message mentions that the operation you try to do is not supported `java.lang.UnsupportedOperationException: Not supported`
