### ISSUE TITLE
Expandable + filtering - crash and problems

### ISSUE THREAD

**Issue by MFlisar** [mikepenz/FastAdapter#885]
**General problem**
In general, if you use expandable items and filtering together, you always lose the expandable state during filtering. This is really a problem if you want to filter and suddenly the expanded item containing the item that you want to filter out is gone because it's parent is collapsed.

**Crash**
A side effect of this behaviour is following crash if you collapse/expand items after filtering your views.

**Exception**

    kotlin.TypeCastException: null cannot be cast to non-null type kotlin.collections.List<Item>
        at com.mikepenz.fastadapter.adapters.ItemFilter.publishResults(ItemFilter.kt:104)
        at android.widget.Filter$ResultsHandler.handleMessage(Filter.java:282)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:6986)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)

## Details
- [ ] Used library version: 5.0.0

**Comment by mikepenz** [comment]
@MFlisar the provided filter code is not optimized for cases with expandables at once. I am sure there are a few optimizations possible / needed to make ti really work well. 

I am open for improvements / PRs to improve the behavior in this matter. 

But it was not a priority when creating, as it is a rare and more specialized usecase.

**Comment by ahmedrem55538** [comment]
> **مشكلة عامة** بشكل عام ، إذا كنت تستخدم عناصر قابلة للتوسيع والتصفية معًا ، فستفقد دائمًا الحالة القابلة للتوسيع أثناء التصفية. هذه مشكلة حقًا إذا كنت تريد التصفية وفجأة اختفى العنصر الموسع الذي يحتوي على العنصر الذي تريد تصفيته لأنه تم طي العنصر الأصل. بالإضافة إلى ذلك ، فإن توسيع عنصر أثناء نشاط الفلتر لا يحترم عامل التصفية النشط الحالي كما يبدو ، وأرى أنه يتم دائمًا توسيع جميع العناصر الفرعية للعنصر بغض النظر عن عامل التصفية الحالي.
> 
> **الأعطال** من الآثار الجانبية لهذا السلوك الانهيار إذا قمت بطي / توسيع العناصر بعد تصفية طرق العرض الخاصة بك.
> 
> إذا رغبت في ذلك ، يمكنني أن أعطيك مثالًا لرمز مع مكتبة صغيرة أعيد كتابتها حاليًا في kotlin وهي ليست بعيدة بعد ولكن يمكنني إعادة إنتاج هذه المشكلة بسهولة.
> 
> **استثناء**
> 
> ```
> kotlin.TypeCastException: null cannot be cast to non-null type kotlin.collections.List<Item>
>     at com.mikepenz.fastadapter.adapters.ItemFilter.publishResults(ItemFilter.kt:104)
>     at android.widget.Filter$ResultsHandler.handleMessage(Filter.java:282)
>     at android.os.Handler.dispatchMessage(Handler.java:106)
>     at android.os.Looper.loop(Looper.java:214)
>     at android.app.ActivityThread.main(ActivityThread.java:6986)
>     at java.lang.reflect.Method.invoke(Native Method)
>     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
>     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
> ```
> 
> ## تفاصيل
> * [] إصدار المكتبة المستخدمة: 5.0.0

Hi

**Comment by usandourkids525** [comment]
Add love for self and other's

**Comment by androidacy-user** [comment]
For us on 5.7.0, expanding an item after search causes search(filter) to stop working. No crashes, just calling filter() no longer does anything
