### ISSUE TITLE
IllegalArgumentException: Tmp detached view should be removed from RecyclerView before it can be recycled

### ISSUE THREAD

**Issue by Z-13** [mikepenz/FastAdapter#889]
I've expanded a RecyclerView:
```
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <androidx.core.widget.NestedScrollView
        android:layout_width="0dp"
        android:layout_height="0dp"
        android:background="@color/background"
        android:fillViewport="true"
        android:orientation="vertical"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent">

        <androidx.constraintlayout.widget.ConstraintLayout
            android:id="@+id/parent"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:paddingBottom="96dp"
            android:animateLayoutChanges="true">

		<TextView/>

		<androidx.recyclerview.widget.RecyclerView
						android:id="@+id/myRv"
						android:layout_width="0dp"
						android:layout_height="wrap_content"
						android:layout_marginTop="8dp"
						android:layout_marginStart="16dp"
						android:layout_marginEnd="16dp"
						android:orientation="vertical"
						app:layout_constraintEnd_toEndOf="parent"
						app:layout_constraintStart_toStartOf="parent"
						app:layout_constraintTop_toBottomOf="@id/myTitle" />

		<TextView/>
		<RecyclerView/>
						
		</androidx.constraintlayout.widget.ConstraintLayout>
	</androidx.core.widget.NestedScrollView>
</androidx.constraintlayout.widget.ConstraintLayout>

```

For animation other items(texts, layout and etc.) I added:
`android:animateLayoutChanges="true"`
for the inner _ConstraintLayout_
+
`parent.layoutTransition.enableTransitionType(LayoutTransition.CHANGING)`

And create my rv:
```
myAdapter = FastItemAdapter()
myAdapter.getExpandableExtension()

val layoutManager = LinearLayoutManager(activity)

myRv.layoutManager = layoutManager
myRv.itemAnimator = SlideDownAlphaAnimator()
myRv.isNestedScrollingEnabled = false

myRv.adapter = myAdapter 
```

And If I tap fast on my recycler's items then I get this:
```
java.lang.IllegalArgumentException: Tmp detached view should be removed from RecyclerView before it can be recycled: ViewHolder{8f7bb5f position=0 id=-12, oldPos=-1, pLpos:-1 update removed tmpDetached no parent} androidx.recyclerview.widget.RecyclerView{3503e37 VFED..... ......ID 42,2419-1038,2679 #7f0a0200 app:id/myRv}, adapter:com.mikepenz.fastadapter.adapters.FastItemAdapter@27667ff, layout:androidx.recyclerview.widget.LinearLayoutManager@e5429cc, context:com.vinilink.app.features.activities.main.MainActivity@e9b8673
        at androidx.recyclerview.widget.RecyclerView$Recycler.recycleViewHolderInternal(RecyclerView.java:6439)
        at androidx.recyclerview.widget.RecyclerView.removeAnimatingView(RecyclerView.java:1456)
        at androidx.recyclerview.widget.RecyclerView$ItemAnimatorRestoreListener.onAnimationFinished(RecyclerView.java:12699)
        at androidx.recyclerview.widget.RecyclerView$ItemAnimator.dispatchAnimationFinished(RecyclerView.java:13199)
        at androidx.recyclerview.widget.SimpleItemAnimator.dispatchAddFinished(SimpleItemAnimator.java:302)
        at com.mikepenz.itemanimators.BaseItemAnimator$5.onAnimationEnd(BaseItemAnimator.java:294)
        at androidx.core.view.ViewPropertyAnimatorCompat$1.onAnimationEnd(ViewPropertyAnimatorCompat.java:747)
        at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd(ViewPropertyAnimator.java:1111)
        at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:554)
        at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1242)
        at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1484)
        at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
        at android.animation.AnimationHandler.access$100(AnimationHandler.java:37)
        at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:964)
        at android.view.Choreographer.doCallbacks(Choreographer.java:790)
        at android.view.Choreographer.doFrame(Choreographer.java:721)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:951)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
```

If I remove:
`android:animateLayoutChanges="true"`
+
`parent.layoutTransition.enableTransitionType(LayoutTransition.CHANGING)`
Everything is OK, but not beautiful animation other items.

And one more - If tap fast on the parent expanded items(in my project or in the lib demo) then U can see how it will be jump up. And it looks strange.

**Comment by mikepenz** [comment]
sounds like either a issue with RV itself. wth the core adapter form RV, with the animator or with the animation of layout changes. 

Can't see anything which would point to code from the Adapter

**Comment by Z-13** [comment]
@mikepenz 
And this too?
> And one more - If tap fast on the parent expanded items(in my project or in the lib demo) then U can see how it will be jump up. And it looks strange.

**Comment by mikepenz** [comment]
@Z-13 that's simply how the animator works. that's nothing directly the lib controls. 

You can try to use a different animator for example like an alpha animator. 
Alternative no animator at all would also remove this effect.

**Comment by mikepenz** [comment]
I hope this answered your concerns :)
