### ISSUE TITLE
Cannot call this method in a scroll callback. (EndlessRecyclerOnScrollListener)

### ISSUE THREAD

**Issue by Z-13** [mikepenz/FastAdapter#896]
@mikepenz ;)
I do everything how into example(https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/EndlessScrollListActivity.kt):

```
private lateinit var myAdapter: GenericFastItemAdapter
private lateinit var footerAdapter: GenericItemAdapter

lateinit var endlessRecyclerOnScrollListener: EndlessRecyclerOnScrollListener
	
	
myAdapter = FastItemAdapter()

footerAdapter = items()
myAdapter.addAdapter(1, footerAdapter)

myAdapter.onClickListener = { view, adapter, item, position ->
	presenter.onItemClicked(item)

	false
}

val layoutManager = LinearLayoutManager(activity)

rvItems.layoutManager = layoutManager
rvItems.adapter = myAdapter


endlessRecyclerOnScrollListener = object : EndlessRecyclerOnScrollListener(footerAdapter) {
	override fun onLoadMore(currentPage: Int) {
		footerAdapter.clear()

		val progressItem = ProgressItem()
		progressItem.isEnabled = false

		footerAdapter.add(progressItem)

		presenter.goToNextPage(currentPage)
}

rvWineries.addOnScrollListener(endlessRecyclerOnScrollListener)
...
fun showData(items: List<MyItem>) {
	FastAdapterDiffUtil[myAdapter.itemAdapter] = items
}
```

And after start scroll I look at my console this(more times):
> Cannot call this method in a scroll callback. Scroll callbacks mightbe run during a measure & layout pass where you cannot change theRecyclerView data. Any method call that might change the structureof the RecyclerView or the adapter contents should be postponed tothe next frame.
>     java.lang.IllegalStateException:  androidx.recyclerview.widget.RecyclerView{3699815 VFED..... ......ID 0,527-1080,1626 #7f0a01de app:id/rvItems}, adapter:com.mikepenz.fastadapter.adapters.FastItemAdapter@58a572a, layout:androidx.recyclerview.widget.LinearLayoutManager@6f2191b, context:com.myapp.features.activities.main.MainActivity@7921673

Maybe this(https://github.com/android/plaid/pull/226/files/e9a8e234aff0db9ff04c13720bd85930cfa4a40c) will be helpful.

**Comment by mikepenz** [comment]
@Z-13 I'd not count this as a bug of the library, as I think the user should have the control what to act on. 

So I'd propose to move the code onto the next frame via the post :) 

In the sample we do the same: https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/EndlessScrollListActivity.kt#L98-L103

Just for showcasing purposes we delay it by 2 seconds to have a "slow" loading

**Comment by Z-13** [comment]
Yes, I try add Handler, but 2 warnings indicates to others lines:

```
at androidx.recyclerview.widget.RecyclerView.assertNotInLayoutOrScroll(RecyclerView.java:3061)
        at androidx.recyclerview.widget.RecyclerView$RecyclerViewDataObserver.onItemRangeRemoved(RecyclerView.java:5563)
        at androidx.recyclerview.widget.RecyclerView$AdapterDataObservable.notifyItemRangeRemoved(RecyclerView.java:12288)
        at androidx.recyclerview.widget.RecyclerView$Adapter.notifyItemRangeRemoved(RecyclerView.java:7532)
        at com.mikepenz.fastadapter.FastAdapter.notifyAdapterItemRangeRemoved(FastAdapter.kt:748)
        at com.mikepenz.fastadapter.utils.DefaultItemListImpl.clear(DefaultItemListImpl.kt:59)
        at com.mikepenz.fastadapter.adapters.ModelAdapter.clear(ModelAdapter.kt:397)
        at com.app.features.....MyFragment$initRv$2.onLoadMore(MyFragment.kt:136)
        at com.mikepenz.fastadapter.scroll.EndlessRecyclerOnScrollListener.onScrolled(EndlessRecyclerOnScrollListener.kt:143)
        at androidx.recyclerview.widget.RecyclerView.dispatchOnScrolled(RecyclerView.java:5173)
        at androidx.recyclerview.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:5338)
		
		
layout:androidx.recyclerview.widget.LinearLayoutManager@958a091, context:com.app.features.activities.main.MainActivity@ff17b2e
        at androidx.recyclerview.widget.RecyclerView.assertNotInLayoutOrScroll(RecyclerView.java:3061)
        at androidx.recyclerview.widget.RecyclerView$RecyclerViewDataObserver.onItemRangeInserted(RecyclerView.java:5555)
        at androidx.recyclerview.widget.RecyclerView$AdapterDataObservable.notifyItemRangeInserted(RecyclerView.java:12278)
        at androidx.recyclerview.widget.RecyclerView$Adapter.notifyItemRangeInserted(RecyclerView.java:7498)
        at com.mikepenz.fastadapter.FastAdapter.notifyAdapterItemRangeInserted(FastAdapter.kt:723)
        at com.mikepenz.fastadapter.utils.DefaultItemListImpl.addAll(DefaultItemListImpl.kt:70)
        at com.mikepenz.fastadapter.adapters.ModelAdapter.addInternal(ModelAdapter.kt:302)
        at com.mikepenz.fastadapter.adapters.ModelAdapter.add(ModelAdapter.kt:293)
        at com.mikepenz.fastadapter.adapters.ModelAdapter.add(ModelAdapter.kt:284)
        at com.vinilink.app.features.....MyFragment$initRv$2.onLoadMore(MyFragment.kt:141)
        at com.mikepenz.fastadapter.scroll.EndlessRecyclerOnScrollListener.onScrolled(EndlessRecyclerOnScrollListener.kt:143)
        at androidx.recyclerview.widget.RecyclerView.dispatchOnScrolled(RecyclerView.java:5173)
```

And this's:
`footerAdapter.clear()`
https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/EndlessScrollListActivity.kt#L92

and this:
`footerAdapter.add(progressItem)`
https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/EndlessScrollListActivity.kt#L95

**Comment by mikepenz** [comment]
one is here in your code:
```
at com.app.features.....MyFragment$initRv$2.onLoadMore(MyFragment.kt:136)
```

and the other here in your code:
```
at com.vinilink.app.features.....MyFragment$initRv$2.onLoadMore(MyFragment.kt:141)
```

**Comment by mikepenz** [comment]
Please report back if you were able to resolve the problem my having the respective calls done on the UI thread?

Closing for the time being. Please re-open if more is needed
