### ISSUE TITLE
How to use both expandable and paging

### ISSUE THREAD

**Issue by jDilshodbek** [mikepenz/FastAdapter#924]
## Can't use both expandable and paging at the same time.

- Expandable requires parent and child generic items, paging requires single model item to use.

## Details
- Are there any samples to use paging and advanced sample at the same time?

I had crash 
` java.lang.UnsupportedOperationException: Not supported
        at com.mikepenz.fastadapter.paged.PagedModelAdapter.addInternal(PagedModelAdapter.kt:221)
        at com.mikepenz.fastadapter.expandable.ExpandableExtension.expand(ExpandableExtension.kt:396)
        at com.mikepenz.fastadapter.expandable.ExpandableExtension.toggleExpandable(ExpandableExtension.kt:314)
        at com.mikepenz.fastadapter.expandable.ExpandableExtension.toggleExpandable$default(ExpandableExtension.kt:309)
        at com.mikepenz.fastadapter.expandable.ExpandableExtension$onClick$1.invoke(ExpandableExtension.kt:173)
        at com.mikepenz.fastadapter.expandable.ExpandableExtension$onClick$1.invoke(ExpandableExtension.kt:59)
        at com.mikepenz.fastadapter.expandable.ExpandableExtensionKt.ifExpandable(ExpandableExtension.kt:45)
        at com.mikepenz.fastadapter.expandable.ExpandableExtension.onClick(ExpandableExtension.kt:171)
        at com.mikepenz.fastadapter.FastAdapter$viewClickListener$1.onClick(FastAdapter.kt:116)
        at com.mikepenz.fastadapter.utils.EventHookUtilKt$attachToView$1.onClick(EventHookUtil.kt:53)
        at android.view.View.performClick(View.java:7125)
        at android.view.View.performClickInternal(View.java:7102)
        at android.view.View.access$3500(View.java:801)
        at android.view.View$PerformClick.run(View.java:27336)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)`

**Comment by mikepenz** [comment]
@jDilshodbek due to the way the paged adapter works (with the system paging) It sadly won't support expandable at this time

**Comment by jDilshodbek** [comment]
Will you consider adding this feature in the future?

**Comment by mikepenz** [comment]
@jDilshodbek it's more like a limitation of the way paging functions as of the paging library. so I doubt it will be possible
